-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity toe_process_ipv4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    s_axis_tcp_data_TVALID : IN STD_LOGIC;
    rxEng_dataBuffer0_V_din : OUT STD_LOGIC_VECTOR (576 downto 0);
    rxEng_dataBuffer0_V_full_n : IN STD_LOGIC;
    rxEng_dataBuffer0_V_write : OUT STD_LOGIC;
    rx_process2dropLengt_1_din : OUT STD_LOGIC_VECTOR (3 downto 0);
    rx_process2dropLengt_1_full_n : IN STD_LOGIC;
    rx_process2dropLengt_1_write : OUT STD_LOGIC;
    rxEng_ipMetaFifo_V_t_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    rxEng_ipMetaFifo_V_t_full_n : IN STD_LOGIC;
    rxEng_ipMetaFifo_V_t_write : OUT STD_LOGIC;
    rxEng_ipMetaFifo_V_o_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    rxEng_ipMetaFifo_V_o_full_n : IN STD_LOGIC;
    rxEng_ipMetaFifo_V_o_write : OUT STD_LOGIC;
    rxEng_ipMetaFifo_V_l_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    rxEng_ipMetaFifo_V_l_full_n : IN STD_LOGIC;
    rxEng_ipMetaFifo_V_l_write : OUT STD_LOGIC;
    s_axis_tcp_data_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    s_axis_tcp_data_TREADY : OUT STD_LOGIC;
    s_axis_tcp_data_TKEEP : IN STD_LOGIC_VECTOR (63 downto 0);
    s_axis_tcp_data_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of toe_process_ipv4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv25_9F : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000010011111";
    constant ap_const_lv159_lc_1 : STD_LOGIC_VECTOR (158 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv160_lc_3 : STD_LOGIC_VECTOR (159 downto 0) := "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv160_lc_4 : STD_LOGIC_VECTOR (159 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv160_lc_5 : STD_LOGIC_VECTOR (159 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal tmp_nbreadreq_fu_110_p5 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal tmp_reg_469 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln73_reg_504 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op46_write_state2 : BOOLEAN;
    signal metaWritten_load_reg_509 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op49_write_state2 : BOOLEAN;
    signal io_acc_block_signal_op58 : STD_LOGIC;
    signal ap_predicate_op58_write_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal header_ready : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal header_idx_5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal header_header_V_6 : STD_LOGIC_VECTOR (159 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000101";
    signal metaWritten : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal s_axis_tcp_data_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal rxEng_dataBuffer0_V_blk_n : STD_LOGIC;
    signal rx_process2dropLengt_1_blk_n : STD_LOGIC;
    signal rxEng_ipMetaFifo_V_t_blk_n : STD_LOGIC;
    signal rxEng_ipMetaFifo_V_o_blk_n : STD_LOGIC;
    signal rxEng_ipMetaFifo_V_l_blk_n : STD_LOGIC;
    signal tmp_data_V_reg_473 : STD_LOGIC_VECTOR (511 downto 0);
    signal tmp_keep_V_reg_478 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_last_V_reg_483 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln67_fu_327_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal header_ready_load_load_fu_207_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln73_fu_333_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal metaWritten_load_load_fu_339_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_phi_mux_write_flag_1_i_i_phi_fu_162_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_write_flag_1_i_i_reg_159 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_phi_ln73_reg_170 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter1_phi_ln73_reg_170 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_metaWritten_flag_1_i_reg_179 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_metaWritten_flag_1_i_reg_179 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln69_fu_434_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_allocacmp_header_ready_load : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln69_fu_439_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_allocacmp_header_idx_5_load : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_s_fu_315_p2 : STD_LOGIC_VECTOR (159 downto 0);
    signal xor_ln69_fu_429_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln69_fu_446_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_allocacmp_metaWritten_load : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_V_fu_355_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal Lo_assign_fu_215_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal trunc_ln414_fu_237_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln414_fu_231_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal st3_fu_241_p3 : STD_LOGIC_VECTOR (159 downto 0);
    signal tmp_V_3_fu_223_p1 : STD_LOGIC_VECTOR (159 downto 0);
    signal select_ln414_fu_249_p3 : STD_LOGIC_VECTOR (159 downto 0);
    signal tmp_223_fu_257_p4 : STD_LOGIC_VECTOR (159 downto 0);
    signal select_ln414_2_fu_275_p3 : STD_LOGIC_VECTOR (159 downto 0);
    signal select_ln414_3_fu_283_p3 : STD_LOGIC_VECTOR (159 downto 0);
    signal and_ln414_fu_291_p2 : STD_LOGIC_VECTOR (159 downto 0);
    signal xor_ln414_fu_297_p2 : STD_LOGIC_VECTOR (159 downto 0);
    signal select_ln414_1_fu_267_p3 : STD_LOGIC_VECTOR (159 downto 0);
    signal and_ln414_4_fu_303_p2 : STD_LOGIC_VECTOR (159 downto 0);
    signal and_ln414_5_fu_309_p2 : STD_LOGIC_VECTOR (159 downto 0);
    signal p_Result_138_1_i_i_fu_392_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_138_i_i_fu_382_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln_fu_410_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal agg_result_V_0_1_i_i_fu_402_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln214_3_fu_418_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_98 : BOOLEAN;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_metaWritten_flag_1_i_reg_179_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (metaWritten_load_load_fu_339_p1 = ap_const_lv1_0) and (or_ln73_fu_333_p2 = ap_const_lv1_1) and (tmp_nbreadreq_fu_110_p5 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter1_metaWritten_flag_1_i_reg_179 <= ap_const_lv1_1;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (metaWritten_load_load_fu_339_p1 = ap_const_lv1_1) and (or_ln73_fu_333_p2 = ap_const_lv1_1) and (tmp_nbreadreq_fu_110_p5 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (or_ln73_fu_333_p2 = ap_const_lv1_0) and (tmp_nbreadreq_fu_110_p5 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                ap_phi_reg_pp0_iter1_metaWritten_flag_1_i_reg_179 <= ap_const_lv1_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter1_metaWritten_flag_1_i_reg_179 <= ap_phi_reg_pp0_iter0_metaWritten_flag_1_i_reg_179;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_phi_ln73_reg_170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_98)) then
                if (((header_ready_load_load_fu_207_p1 = ap_const_lv1_0) and (tmp_nbreadreq_fu_110_p5 = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter1_phi_ln73_reg_170 <= add_ln67_fu_327_p2;
                elsif (((header_ready_load_load_fu_207_p1 = ap_const_lv1_1) and (tmp_nbreadreq_fu_110_p5 = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter1_phi_ln73_reg_170 <= ap_sig_allocacmp_header_idx_5_load;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_phi_ln73_reg_170 <= ap_phi_reg_pp0_iter0_phi_ln73_reg_170;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (header_ready_load_load_fu_207_p1 = ap_const_lv1_0) and (tmp_nbreadreq_fu_110_p5 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                header_header_V_6 <= p_Result_s_fu_315_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_469 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                header_idx_5 <= select_ln69_fu_439_p3;
                header_ready <= and_ln69_fu_434_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_469 = ap_const_lv1_1) and (or_ln69_fu_446_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                metaWritten <= xor_ln69_fu_429_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_nbreadreq_fu_110_p5 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                metaWritten_load_reg_509 <= ap_sig_allocacmp_metaWritten_load;
                or_ln73_reg_504 <= or_ln73_fu_333_p2;
                tmp_data_V_reg_473 <= s_axis_tcp_data_TDATA;
                tmp_keep_V_reg_478 <= s_axis_tcp_data_TKEEP;
                tmp_last_V_reg_483 <= s_axis_tcp_data_TLAST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_reg_469 <= tmp_nbreadreq_fu_110_p5;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    Lo_assign_fu_215_p3 <= (ap_sig_allocacmp_header_idx_5_load & ap_const_lv9_0);
    add_ln67_fu_327_p2 <= std_logic_vector(unsigned(ap_const_lv16_1) + unsigned(ap_sig_allocacmp_header_idx_5_load));
    agg_result_V_0_1_i_i_fu_402_p3 <= (p_Result_138_1_i_i_fu_392_p4 & p_Result_138_i_i_fu_382_p4);
    and_ln414_4_fu_303_p2 <= (xor_ln414_fu_297_p2 and header_header_V_6);
    and_ln414_5_fu_309_p2 <= (select_ln414_1_fu_267_p3 and and_ln414_fu_291_p2);
    and_ln414_fu_291_p2 <= (select_ln414_3_fu_283_p3 and select_ln414_2_fu_275_p3);
    and_ln69_fu_434_p2 <= (xor_ln69_fu_429_p2 and or_ln73_reg_504);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, s_axis_tcp_data_TVALID, tmp_nbreadreq_fu_110_p5, rxEng_dataBuffer0_V_full_n, ap_predicate_op46_write_state2, rx_process2dropLengt_1_full_n, ap_predicate_op49_write_state2, io_acc_block_signal_op58, ap_predicate_op58_write_state2)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((io_acc_block_signal_op58 = ap_const_logic_0) and (ap_predicate_op58_write_state2 = ap_const_boolean_1)) or ((rx_process2dropLengt_1_full_n = ap_const_logic_0) and (ap_predicate_op49_write_state2 = ap_const_boolean_1)) or ((rxEng_dataBuffer0_V_full_n = ap_const_logic_0) and (ap_predicate_op46_write_state2 = ap_const_boolean_1)))) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_nbreadreq_fu_110_p5 = ap_const_lv1_1) and (s_axis_tcp_data_TVALID = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, s_axis_tcp_data_TVALID, tmp_nbreadreq_fu_110_p5, rxEng_dataBuffer0_V_full_n, ap_predicate_op46_write_state2, rx_process2dropLengt_1_full_n, ap_predicate_op49_write_state2, io_acc_block_signal_op58, ap_predicate_op58_write_state2)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((io_acc_block_signal_op58 = ap_const_logic_0) and (ap_predicate_op58_write_state2 = ap_const_boolean_1)) or ((rx_process2dropLengt_1_full_n = ap_const_logic_0) and (ap_predicate_op49_write_state2 = ap_const_boolean_1)) or ((rxEng_dataBuffer0_V_full_n = ap_const_logic_0) and (ap_predicate_op46_write_state2 = ap_const_boolean_1)))) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_nbreadreq_fu_110_p5 = ap_const_lv1_1) and (s_axis_tcp_data_TVALID = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, s_axis_tcp_data_TVALID, tmp_nbreadreq_fu_110_p5, rxEng_dataBuffer0_V_full_n, ap_predicate_op46_write_state2, rx_process2dropLengt_1_full_n, ap_predicate_op49_write_state2, io_acc_block_signal_op58, ap_predicate_op58_write_state2)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((io_acc_block_signal_op58 = ap_const_logic_0) and (ap_predicate_op58_write_state2 = ap_const_boolean_1)) or ((rx_process2dropLengt_1_full_n = ap_const_logic_0) and (ap_predicate_op49_write_state2 = ap_const_boolean_1)) or ((rxEng_dataBuffer0_V_full_n = ap_const_logic_0) and (ap_predicate_op46_write_state2 = ap_const_boolean_1)))) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_nbreadreq_fu_110_p5 = ap_const_lv1_1) and (s_axis_tcp_data_TVALID = ap_const_logic_0)))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start, ap_done_reg, s_axis_tcp_data_TVALID, tmp_nbreadreq_fu_110_p5)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_nbreadreq_fu_110_p5 = ap_const_lv1_1) and (s_axis_tcp_data_TVALID = ap_const_logic_0)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(rxEng_dataBuffer0_V_full_n, ap_predicate_op46_write_state2, rx_process2dropLengt_1_full_n, ap_predicate_op49_write_state2, io_acc_block_signal_op58, ap_predicate_op58_write_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (((io_acc_block_signal_op58 = ap_const_logic_0) and (ap_predicate_op58_write_state2 = ap_const_boolean_1)) or ((rx_process2dropLengt_1_full_n = ap_const_logic_0) and (ap_predicate_op49_write_state2 = ap_const_boolean_1)) or ((rxEng_dataBuffer0_V_full_n = ap_const_logic_0) and (ap_predicate_op46_write_state2 = ap_const_boolean_1)));
    end process;


    ap_condition_98_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_98 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_write_flag_1_i_i_phi_fu_162_p4_assign_proc : process(tmp_nbreadreq_fu_110_p5, header_ready_load_load_fu_207_p1, ap_phi_reg_pp0_iter0_write_flag_1_i_i_reg_159)
    begin
        if ((tmp_nbreadreq_fu_110_p5 = ap_const_lv1_1)) then
            if ((header_ready_load_load_fu_207_p1 = ap_const_lv1_0)) then 
                ap_phi_mux_write_flag_1_i_i_phi_fu_162_p4 <= ap_const_lv1_1;
            elsif ((header_ready_load_load_fu_207_p1 = ap_const_lv1_1)) then 
                ap_phi_mux_write_flag_1_i_i_phi_fu_162_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_write_flag_1_i_i_phi_fu_162_p4 <= ap_phi_reg_pp0_iter0_write_flag_1_i_i_reg_159;
            end if;
        else 
            ap_phi_mux_write_flag_1_i_i_phi_fu_162_p4 <= ap_phi_reg_pp0_iter0_write_flag_1_i_i_reg_159;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_metaWritten_flag_1_i_reg_179 <= "X";
    ap_phi_reg_pp0_iter0_phi_ln73_reg_170 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_write_flag_1_i_i_reg_159 <= "X";

    ap_predicate_op46_write_state2_assign_proc : process(tmp_reg_469, or_ln73_reg_504)
    begin
                ap_predicate_op46_write_state2 <= ((or_ln73_reg_504 = ap_const_lv1_1) and (tmp_reg_469 = ap_const_lv1_1));
    end process;


    ap_predicate_op49_write_state2_assign_proc : process(tmp_reg_469, or_ln73_reg_504, metaWritten_load_reg_509)
    begin
                ap_predicate_op49_write_state2 <= ((metaWritten_load_reg_509 = ap_const_lv1_0) and (or_ln73_reg_504 = ap_const_lv1_1) and (tmp_reg_469 = ap_const_lv1_1));
    end process;


    ap_predicate_op58_write_state2_assign_proc : process(tmp_reg_469, or_ln73_reg_504, metaWritten_load_reg_509)
    begin
                ap_predicate_op58_write_state2 <= ((metaWritten_load_reg_509 = ap_const_lv1_0) and (or_ln73_reg_504 = ap_const_lv1_1) and (tmp_reg_469 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_header_idx_5_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_469, header_idx_5, ap_block_pp0_stage0, select_ln69_fu_439_p3)
    begin
        if (((tmp_reg_469 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_header_idx_5_load <= select_ln69_fu_439_p3;
        else 
            ap_sig_allocacmp_header_idx_5_load <= header_idx_5;
        end if; 
    end process;


    ap_sig_allocacmp_header_ready_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_469, header_ready, ap_block_pp0_stage0, and_ln69_fu_434_p2)
    begin
        if (((tmp_reg_469 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_header_ready_load <= and_ln69_fu_434_p2;
        else 
            ap_sig_allocacmp_header_ready_load <= header_ready;
        end if; 
    end process;


    ap_sig_allocacmp_metaWritten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_469, metaWritten, ap_block_pp0_stage0, xor_ln69_fu_429_p2, or_ln69_fu_446_p2)
    begin
        if (((tmp_reg_469 = ap_const_lv1_1) and (or_ln69_fu_446_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_metaWritten_load <= xor_ln69_fu_429_p2;
        else 
            ap_sig_allocacmp_metaWritten_load <= metaWritten;
        end if; 
    end process;

    header_ready_load_load_fu_207_p1 <= ap_sig_allocacmp_header_ready_load;
    icmp_ln414_fu_231_p2 <= "1" when (unsigned(Lo_assign_fu_215_p3) > unsigned(ap_const_lv25_9F)) else "0";
    io_acc_block_signal_op58 <= (rxEng_ipMetaFifo_V_t_full_n and rxEng_ipMetaFifo_V_o_full_n and rxEng_ipMetaFifo_V_l_full_n);
    metaWritten_load_load_fu_339_p1 <= ap_sig_allocacmp_metaWritten_load;
    or_ln69_fu_446_p2 <= (tmp_last_V_reg_483 or ap_phi_reg_pp0_iter1_metaWritten_flag_1_i_reg_179);
    or_ln73_fu_333_p2 <= (ap_sig_allocacmp_header_ready_load or ap_phi_mux_write_flag_1_i_i_phi_fu_162_p4);
    p_Result_138_1_i_i_fu_392_p4 <= header_header_V_6(23 downto 16);
    p_Result_138_i_i_fu_382_p4 <= header_header_V_6(31 downto 24);
    p_Result_s_fu_315_p2 <= (and_ln414_5_fu_309_p2 or and_ln414_4_fu_303_p2);

    rxEng_dataBuffer0_V_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, rxEng_dataBuffer0_V_full_n, ap_predicate_op46_write_state2, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op46_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            rxEng_dataBuffer0_V_blk_n <= rxEng_dataBuffer0_V_full_n;
        else 
            rxEng_dataBuffer0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    rxEng_dataBuffer0_V_din <= ((tmp_last_V_reg_483 & tmp_keep_V_reg_478) & tmp_data_V_reg_473);

    rxEng_dataBuffer0_V_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op46_write_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op46_write_state2 = ap_const_boolean_1))) then 
            rxEng_dataBuffer0_V_write <= ap_const_logic_1;
        else 
            rxEng_dataBuffer0_V_write <= ap_const_logic_0;
        end if; 
    end process;


    rxEng_ipMetaFifo_V_l_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, rxEng_ipMetaFifo_V_l_full_n, ap_predicate_op58_write_state2, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op58_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            rxEng_ipMetaFifo_V_l_blk_n <= rxEng_ipMetaFifo_V_l_full_n;
        else 
            rxEng_ipMetaFifo_V_l_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    rxEng_ipMetaFifo_V_l_din <= std_logic_vector(unsigned(agg_result_V_0_1_i_i_fu_402_p3) - unsigned(zext_ln214_3_fu_418_p1));

    rxEng_ipMetaFifo_V_l_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op58_write_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op58_write_state2 = ap_const_boolean_1))) then 
            rxEng_ipMetaFifo_V_l_write <= ap_const_logic_1;
        else 
            rxEng_ipMetaFifo_V_l_write <= ap_const_logic_0;
        end if; 
    end process;


    rxEng_ipMetaFifo_V_o_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, rxEng_ipMetaFifo_V_o_full_n, ap_predicate_op58_write_state2, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op58_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            rxEng_ipMetaFifo_V_o_blk_n <= rxEng_ipMetaFifo_V_o_full_n;
        else 
            rxEng_ipMetaFifo_V_o_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    rxEng_ipMetaFifo_V_o_din <= header_header_V_6(159 downto 128);

    rxEng_ipMetaFifo_V_o_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op58_write_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op58_write_state2 = ap_const_boolean_1))) then 
            rxEng_ipMetaFifo_V_o_write <= ap_const_logic_1;
        else 
            rxEng_ipMetaFifo_V_o_write <= ap_const_logic_0;
        end if; 
    end process;


    rxEng_ipMetaFifo_V_t_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, rxEng_ipMetaFifo_V_t_full_n, ap_predicate_op58_write_state2, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op58_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            rxEng_ipMetaFifo_V_t_blk_n <= rxEng_ipMetaFifo_V_t_full_n;
        else 
            rxEng_ipMetaFifo_V_t_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    rxEng_ipMetaFifo_V_t_din <= header_header_V_6(127 downto 96);

    rxEng_ipMetaFifo_V_t_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op58_write_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op58_write_state2 = ap_const_boolean_1))) then 
            rxEng_ipMetaFifo_V_t_write <= ap_const_logic_1;
        else 
            rxEng_ipMetaFifo_V_t_write <= ap_const_logic_0;
        end if; 
    end process;


    rx_process2dropLengt_1_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, rx_process2dropLengt_1_full_n, ap_predicate_op49_write_state2, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op49_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            rx_process2dropLengt_1_blk_n <= rx_process2dropLengt_1_full_n;
        else 
            rx_process2dropLengt_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    rx_process2dropLengt_1_din <= tmp_V_fu_355_p1;

    rx_process2dropLengt_1_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op49_write_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op49_write_state2 = ap_const_boolean_1))) then 
            rx_process2dropLengt_1_write <= ap_const_logic_1;
        else 
            rx_process2dropLengt_1_write <= ap_const_logic_0;
        end if; 
    end process;


    s_axis_tcp_data_TDATA_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, s_axis_tcp_data_TVALID, tmp_nbreadreq_fu_110_p5, ap_block_pp0_stage0)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (tmp_nbreadreq_fu_110_p5 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            s_axis_tcp_data_TDATA_blk_n <= s_axis_tcp_data_TVALID;
        else 
            s_axis_tcp_data_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    s_axis_tcp_data_TREADY_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_nbreadreq_fu_110_p5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_nbreadreq_fu_110_p5 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s_axis_tcp_data_TREADY <= ap_const_logic_1;
        else 
            s_axis_tcp_data_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    select_ln414_1_fu_267_p3 <= 
        tmp_223_fu_257_p4 when (icmp_ln414_fu_231_p2(0) = '1') else 
        tmp_V_3_fu_223_p1;
    select_ln414_2_fu_275_p3 <= 
        ap_const_lv160_lc_3 when (icmp_ln414_fu_231_p2(0) = '1') else 
        ap_const_lv160_lc_4;
    select_ln414_3_fu_283_p3 <= 
        ap_const_lv160_lc_5 when (icmp_ln414_fu_231_p2(0) = '1') else 
        ap_const_lv160_lc_4;
    select_ln414_fu_249_p3 <= 
        st3_fu_241_p3 when (icmp_ln414_fu_231_p2(0) = '1') else 
        tmp_V_3_fu_223_p1;
    select_ln69_fu_439_p3 <= 
        ap_const_lv16_0 when (tmp_last_V_reg_483(0) = '1') else 
        ap_phi_reg_pp0_iter1_phi_ln73_reg_170;
    shl_ln_fu_410_p3 <= (tmp_V_fu_355_p1 & ap_const_lv2_0);
    st3_fu_241_p3 <= (trunc_ln414_fu_237_p1 & ap_const_lv159_lc_1);
    
    tmp_223_fu_257_p4_proc : process(select_ln414_fu_249_p3)
    variable vlo_cpy : STD_LOGIC_VECTOR(160+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(160+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(160 - 1 downto 0);
    variable tmp_223_fu_257_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(160 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(160 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(160 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(8 - 1 downto 0) := ap_const_lv32_9F(8 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(8 - 1 downto 0) := ap_const_lv32_0(8 - 1 downto 0);
        v0_cpy := select_ln414_fu_249_p3;
        if (vlo_cpy(8 - 1 downto 0) > vhi_cpy(8 - 1 downto 0)) then
            vhi_cpy(8-1 downto 0) := std_logic_vector(160-1-unsigned(ap_const_lv32_0(8-1 downto 0)));
            vlo_cpy(8-1 downto 0) := std_logic_vector(160-1-unsigned(ap_const_lv32_9F(8-1 downto 0)));
            for tmp_223_fu_257_p4_i in 0 to 160-1 loop
                v0_cpy(tmp_223_fu_257_p4_i) := select_ln414_fu_249_p3(160-1-tmp_223_fu_257_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(8-1 downto 0)))));

        section := (others=>'0');
        section(8-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(8-1 downto 0)) - unsigned(vlo_cpy(8-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(160-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_223_fu_257_p4 <= resvalue(160-1 downto 0);
    end process;

    tmp_V_3_fu_223_p1 <= s_axis_tcp_data_TDATA(160 - 1 downto 0);
    tmp_V_fu_355_p1 <= header_header_V_6(4 - 1 downto 0);
    tmp_nbreadreq_fu_110_p5 <= (0=>(s_axis_tcp_data_TVALID), others=>'-');
    trunc_ln414_fu_237_p1 <= s_axis_tcp_data_TDATA(1 - 1 downto 0);
    xor_ln414_fu_297_p2 <= (ap_const_lv160_lc_4 xor and_ln414_fu_291_p2);
    xor_ln69_fu_429_p2 <= (tmp_last_V_reg_483 xor ap_const_lv1_1);
    zext_ln214_3_fu_418_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_410_p3),16));
end behav;
