// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module lshiftWordByOctet_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        rxEng_dataBuffer4_V_1_dout,
        rxEng_dataBuffer4_V_1_empty_n,
        rxEng_dataBuffer4_V_1_read,
        rxEng_dataBuffer4_V_2_dout,
        rxEng_dataBuffer4_V_2_empty_n,
        rxEng_dataBuffer4_V_2_read,
        rxEng_dataBuffer4_V_s_dout,
        rxEng_dataBuffer4_V_s_empty_n,
        rxEng_dataBuffer4_V_s_read,
        rxEng_dataBuffer5_V_1_din,
        rxEng_dataBuffer5_V_1_full_n,
        rxEng_dataBuffer5_V_1_write,
        rxEng_dataBuffer5_V_2_din,
        rxEng_dataBuffer5_V_2_full_n,
        rxEng_dataBuffer5_V_2_write,
        rxEng_dataBuffer5_V_s_din,
        rxEng_dataBuffer5_V_s_full_n,
        rxEng_dataBuffer5_V_s_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [511:0] rxEng_dataBuffer4_V_1_dout;
input   rxEng_dataBuffer4_V_1_empty_n;
output   rxEng_dataBuffer4_V_1_read;
input  [63:0] rxEng_dataBuffer4_V_2_dout;
input   rxEng_dataBuffer4_V_2_empty_n;
output   rxEng_dataBuffer4_V_2_read;
input  [0:0] rxEng_dataBuffer4_V_s_dout;
input   rxEng_dataBuffer4_V_s_empty_n;
output   rxEng_dataBuffer4_V_s_read;
output  [511:0] rxEng_dataBuffer5_V_1_din;
input   rxEng_dataBuffer5_V_1_full_n;
output   rxEng_dataBuffer5_V_1_write;
output  [63:0] rxEng_dataBuffer5_V_2_din;
input   rxEng_dataBuffer5_V_2_full_n;
output   rxEng_dataBuffer5_V_2_write;
output  [0:0] rxEng_dataBuffer5_V_s_din;
input   rxEng_dataBuffer5_V_s_full_n;
output   rxEng_dataBuffer5_V_s_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg rxEng_dataBuffer4_V_1_read;
reg rxEng_dataBuffer4_V_2_read;
reg rxEng_dataBuffer4_V_s_read;
reg[511:0] rxEng_dataBuffer5_V_1_din;
reg rxEng_dataBuffer5_V_1_write;
reg[63:0] rxEng_dataBuffer5_V_2_din;
reg rxEng_dataBuffer5_V_2_write;
reg[0:0] rxEng_dataBuffer5_V_s_din;
reg rxEng_dataBuffer5_V_s_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    io_acc_block_signal_op9;
wire   [0:0] ls_writeRemainder_2_s_load_fu_132_p1;
wire   [0:0] tmp_nbreadreq_fu_74_p5;
reg    ap_predicate_op9_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    io_acc_block_signal_op42;
reg   [0:0] ls_writeRemainder_2_s_reg_303;
reg   [0:0] tmp_reg_307;
reg    ap_predicate_op42_write_state2;
wire    io_acc_block_signal_op49;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] ls_writeRemainder_2;
reg   [511:0] prevWord_data_V_14;
reg   [63:0] prevWord_keep_V_9;
reg   [0:0] ls_firstWord_2;
reg    rxEng_dataBuffer5_V_1_blk_n;
wire    ap_block_pp0_stage0;
reg    rxEng_dataBuffer5_V_2_blk_n;
reg    rxEng_dataBuffer5_V_s_blk_n;
reg    rxEng_dataBuffer4_V_1_blk_n;
reg    rxEng_dataBuffer4_V_2_blk_n;
reg    rxEng_dataBuffer4_V_s_blk_n;
wire   [63:0] sendWord_keep_V_fu_219_p3;
reg   [63:0] sendWord_keep_V_reg_314;
wire   [511:0] sendWord_data_V_fu_227_p3;
reg   [511:0] sendWord_data_V_reg_319;
wire   [0:0] sendWord_last_V_fu_235_p2;
reg   [0:0] sendWord_last_V_reg_324;
reg   [95:0] p_Result_i_reg_329;
wire   [11:0] grp_fu_123_p4;
reg   [11:0] p_Result_i_467_reg_334;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] ap_phi_reg_pp0_iter0_ls_firstWord_2_new_0_reg_110;
reg   [0:0] ap_phi_reg_pp0_iter1_ls_firstWord_2_new_0_reg_110;
wire   [0:0] tmp_last_V_fu_153_p1;
wire   [0:0] xor_ln761_fu_253_p2;
reg   [0:0] ap_sig_allocacmp_ls_firstWord_2_load;
reg    ap_block_pp0_stage0_01001;
wire   [511:0] p_Result_s_fu_287_p3;
wire   [63:0] p_Result_80_fu_295_p3;
wire   [51:0] trunc_ln647_13_fu_171_p1;
wire   [415:0] trunc_ln647_fu_161_p1;
wire   [95:0] p_Result_58_i_fu_193_p4;
wire   [63:0] p_Result_82_fu_175_p3;
wire   [63:0] p_Result_84_fu_211_p3;
wire   [511:0] p_Result_81_fu_165_p2;
wire   [511:0] p_Result_83_fu_203_p3;
wire   [11:0] p_Result_57_i_fu_183_p4;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_152;
reg    ap_condition_156;
reg    ap_condition_100;
reg    ap_condition_180;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ls_writeRemainder_2 = 1'd0;
#0 prevWord_data_V_14 = 512'd0;
#0 prevWord_keep_V_9 = 64'd0;
#0 ls_firstWord_2 = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_100)) begin
        if ((1'b1 == ap_condition_156)) begin
            ap_phi_reg_pp0_iter1_ls_firstWord_2_new_0_reg_110 <= 1'd0;
        end else if ((1'b1 == ap_condition_152)) begin
            ap_phi_reg_pp0_iter1_ls_firstWord_2_new_0_reg_110 <= 1'd1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_ls_firstWord_2_new_0_reg_110 <= ap_phi_reg_pp0_iter0_ls_firstWord_2_new_0_reg_110;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_100)) begin
        if ((ls_writeRemainder_2_s_load_fu_132_p1 == 1'd1)) begin
            ls_writeRemainder_2 <= 1'd0;
        end else if ((1'b1 == ap_condition_152)) begin
            ls_writeRemainder_2 <= xor_ln761_fu_253_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_reg_307 == 1'd1) & (ls_writeRemainder_2_s_reg_303 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ls_firstWord_2 <= ap_phi_reg_pp0_iter1_ls_firstWord_2_new_0_reg_110;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ls_writeRemainder_2_s_reg_303 <= ls_writeRemainder_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ls_writeRemainder_2_s_load_fu_132_p1 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_Result_i_467_reg_334 <= {{prevWord_keep_V_9[63:52]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ls_writeRemainder_2_s_load_fu_132_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_Result_i_reg_329 <= {{prevWord_data_V_14[511:416]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_nbreadreq_fu_74_p5 == 1'd1) & (ls_writeRemainder_2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        prevWord_data_V_14 <= rxEng_dataBuffer4_V_1_dout;
        prevWord_keep_V_9 <= rxEng_dataBuffer4_V_2_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_nbreadreq_fu_74_p5 == 1'd1) & (ls_writeRemainder_2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sendWord_data_V_reg_319 <= sendWord_data_V_fu_227_p3;
        sendWord_keep_V_reg_314 <= sendWord_keep_V_fu_219_p3;
        sendWord_last_V_reg_324 <= sendWord_last_V_fu_235_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ls_writeRemainder_2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_reg_307 <= tmp_nbreadreq_fu_74_p5;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_307 == 1'd1) & (ls_writeRemainder_2_s_reg_303 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_ls_firstWord_2_load = ap_phi_reg_pp0_iter1_ls_firstWord_2_new_0_reg_110;
    end else begin
        ap_sig_allocacmp_ls_firstWord_2_load = ls_firstWord_2;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op9_read_state1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        rxEng_dataBuffer4_V_1_blk_n = rxEng_dataBuffer4_V_1_empty_n;
    end else begin
        rxEng_dataBuffer4_V_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op9_read_state1 == 1'b1))) begin
        rxEng_dataBuffer4_V_1_read = 1'b1;
    end else begin
        rxEng_dataBuffer4_V_1_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op9_read_state1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        rxEng_dataBuffer4_V_2_blk_n = rxEng_dataBuffer4_V_2_empty_n;
    end else begin
        rxEng_dataBuffer4_V_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op9_read_state1 == 1'b1))) begin
        rxEng_dataBuffer4_V_2_read = 1'b1;
    end else begin
        rxEng_dataBuffer4_V_2_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op9_read_state1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        rxEng_dataBuffer4_V_s_blk_n = rxEng_dataBuffer4_V_s_empty_n;
    end else begin
        rxEng_dataBuffer4_V_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op9_read_state1 == 1'b1))) begin
        rxEng_dataBuffer4_V_s_read = 1'b1;
    end else begin
        rxEng_dataBuffer4_V_s_read = 1'b0;
    end
end

always @ (*) begin
    if ((((ls_writeRemainder_2_s_reg_303 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op42_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0)))) begin
        rxEng_dataBuffer5_V_1_blk_n = rxEng_dataBuffer5_V_1_full_n;
    end else begin
        rxEng_dataBuffer5_V_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_180)) begin
        if ((ls_writeRemainder_2_s_reg_303 == 1'd1)) begin
            rxEng_dataBuffer5_V_1_din = p_Result_s_fu_287_p3;
        end else if ((ap_predicate_op42_write_state2 == 1'b1)) begin
            rxEng_dataBuffer5_V_1_din = sendWord_data_V_reg_319;
        end else begin
            rxEng_dataBuffer5_V_1_din = 'bx;
        end
    end else begin
        rxEng_dataBuffer5_V_1_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ls_writeRemainder_2_s_reg_303 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op42_write_state2 == 1'b1)))) begin
        rxEng_dataBuffer5_V_1_write = 1'b1;
    end else begin
        rxEng_dataBuffer5_V_1_write = 1'b0;
    end
end

always @ (*) begin
    if ((((ls_writeRemainder_2_s_reg_303 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op42_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0)))) begin
        rxEng_dataBuffer5_V_2_blk_n = rxEng_dataBuffer5_V_2_full_n;
    end else begin
        rxEng_dataBuffer5_V_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_180)) begin
        if ((ls_writeRemainder_2_s_reg_303 == 1'd1)) begin
            rxEng_dataBuffer5_V_2_din = p_Result_80_fu_295_p3;
        end else if ((ap_predicate_op42_write_state2 == 1'b1)) begin
            rxEng_dataBuffer5_V_2_din = sendWord_keep_V_reg_314;
        end else begin
            rxEng_dataBuffer5_V_2_din = 'bx;
        end
    end else begin
        rxEng_dataBuffer5_V_2_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ls_writeRemainder_2_s_reg_303 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op42_write_state2 == 1'b1)))) begin
        rxEng_dataBuffer5_V_2_write = 1'b1;
    end else begin
        rxEng_dataBuffer5_V_2_write = 1'b0;
    end
end

always @ (*) begin
    if ((((ls_writeRemainder_2_s_reg_303 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op42_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0)))) begin
        rxEng_dataBuffer5_V_s_blk_n = rxEng_dataBuffer5_V_s_full_n;
    end else begin
        rxEng_dataBuffer5_V_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_180)) begin
        if ((ls_writeRemainder_2_s_reg_303 == 1'd1)) begin
            rxEng_dataBuffer5_V_s_din = 1'd1;
        end else if ((ap_predicate_op42_write_state2 == 1'b1)) begin
            rxEng_dataBuffer5_V_s_din = sendWord_last_V_reg_324;
        end else begin
            rxEng_dataBuffer5_V_s_din = 'bx;
        end
    end else begin
        rxEng_dataBuffer5_V_s_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ls_writeRemainder_2_s_reg_303 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op42_write_state2 == 1'b1)))) begin
        rxEng_dataBuffer5_V_s_write = 1'b1;
    end else begin
        rxEng_dataBuffer5_V_s_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((ls_writeRemainder_2_s_reg_303 == 1'd1) & (io_acc_block_signal_op49 == 1'b0)) | ((io_acc_block_signal_op42 == 1'b0) & (ap_predicate_op42_write_state2 == 1'b1)))) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((io_acc_block_signal_op9 == 1'b0) & (ap_predicate_op9_read_state1 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((ls_writeRemainder_2_s_reg_303 == 1'd1) & (io_acc_block_signal_op49 == 1'b0)) | ((io_acc_block_signal_op42 == 1'b0) & (ap_predicate_op42_write_state2 == 1'b1)))) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((io_acc_block_signal_op9 == 1'b0) & (ap_predicate_op9_read_state1 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((ls_writeRemainder_2_s_reg_303 == 1'd1) & (io_acc_block_signal_op49 == 1'b0)) | ((io_acc_block_signal_op42 == 1'b0) & (ap_predicate_op42_write_state2 == 1'b1)))) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((io_acc_block_signal_op9 == 1'b0) & (ap_predicate_op9_read_state1 == 1'b1)))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((io_acc_block_signal_op9 == 1'b0) & (ap_predicate_op9_read_state1 == 1'b1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((ls_writeRemainder_2_s_reg_303 == 1'd1) & (io_acc_block_signal_op49 == 1'b0)) | ((io_acc_block_signal_op42 == 1'b0) & (ap_predicate_op42_write_state2 == 1'b1)));
end

always @ (*) begin
    ap_condition_100 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_152 = ((tmp_last_V_fu_153_p1 == 1'd1) & (tmp_nbreadreq_fu_74_p5 == 1'd1) & (ls_writeRemainder_2 == 1'd0));
end

always @ (*) begin
    ap_condition_156 = ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (tmp_last_V_fu_153_p1 == 1'd0) & (ls_writeRemainder_2 == 1'd0));
end

always @ (*) begin
    ap_condition_180 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_ls_firstWord_2_new_0_reg_110 = 'bx;

always @ (*) begin
    ap_predicate_op42_write_state2 = ((tmp_reg_307 == 1'd1) & (ls_writeRemainder_2_s_reg_303 == 1'd0));
end

always @ (*) begin
    ap_predicate_op9_read_state1 = ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ls_writeRemainder_2 == 1'd0));
end

assign grp_fu_123_p4 = {{prevWord_keep_V_9[63:52]}};

assign io_acc_block_signal_op42 = (rxEng_dataBuffer5_V_s_full_n & rxEng_dataBuffer5_V_2_full_n & rxEng_dataBuffer5_V_1_full_n);

assign io_acc_block_signal_op49 = (rxEng_dataBuffer5_V_s_full_n & rxEng_dataBuffer5_V_2_full_n & rxEng_dataBuffer5_V_1_full_n);

assign io_acc_block_signal_op9 = (rxEng_dataBuffer4_V_s_empty_n & rxEng_dataBuffer4_V_2_empty_n & rxEng_dataBuffer4_V_1_empty_n);

assign ls_writeRemainder_2_s_load_fu_132_p1 = ls_writeRemainder_2;

assign p_Result_57_i_fu_183_p4 = {{rxEng_dataBuffer4_V_2_dout[63:52]}};

assign p_Result_58_i_fu_193_p4 = {{prevWord_data_V_14[511:416]}};

assign p_Result_80_fu_295_p3 = {{52'd0}, {p_Result_i_467_reg_334}};

assign p_Result_81_fu_165_p2 = rxEng_dataBuffer4_V_1_dout << 512'd96;

assign p_Result_82_fu_175_p3 = {{trunc_ln647_13_fu_171_p1}, {12'd4095}};

assign p_Result_83_fu_203_p3 = {{trunc_ln647_fu_161_p1}, {p_Result_58_i_fu_193_p4}};

assign p_Result_84_fu_211_p3 = {{trunc_ln647_13_fu_171_p1}, {grp_fu_123_p4}};

assign p_Result_s_fu_287_p3 = {{416'd0}, {p_Result_i_reg_329}};

assign sendWord_data_V_fu_227_p3 = ((ap_sig_allocacmp_ls_firstWord_2_load[0:0] === 1'b1) ? p_Result_81_fu_165_p2 : p_Result_83_fu_203_p3);

assign sendWord_keep_V_fu_219_p3 = ((ap_sig_allocacmp_ls_firstWord_2_load[0:0] === 1'b1) ? p_Result_82_fu_175_p3 : p_Result_84_fu_211_p3);

assign sendWord_last_V_fu_235_p2 = ((p_Result_57_i_fu_183_p4 == 12'd0) ? 1'b1 : 1'b0);

assign tmp_last_V_fu_153_p1 = rxEng_dataBuffer4_V_s_dout;

assign tmp_nbreadreq_fu_74_p5 = (rxEng_dataBuffer4_V_s_empty_n & rxEng_dataBuffer4_V_2_empty_n & rxEng_dataBuffer4_V_1_empty_n);

assign trunc_ln647_13_fu_171_p1 = rxEng_dataBuffer4_V_2_dout[51:0];

assign trunc_ln647_fu_161_p1 = rxEng_dataBuffer4_V_1_dout[415:0];

assign xor_ln761_fu_253_p2 = (sendWord_last_V_fu_235_p2 ^ 1'd1);

endmodule //lshiftWordByOctet_2
