// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module processPseudoHeader (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        rxEng_dataBuffer2_V_dout,
        rxEng_dataBuffer2_V_empty_n,
        rxEng_dataBuffer2_V_read,
        rxEng_checksumValidF_1_dout,
        rxEng_checksumValidF_1_empty_n,
        rxEng_checksumValidF_1_read,
        rxEng_dataBuffer3a_V_din,
        rxEng_dataBuffer3a_V_full_n,
        rxEng_dataBuffer3a_V_write,
        rxEng_headerMetaFifo_20_din,
        rxEng_headerMetaFifo_20_full_n,
        rxEng_headerMetaFifo_20_write,
        rxEng_headerMetaFifo_12_din,
        rxEng_headerMetaFifo_12_full_n,
        rxEng_headerMetaFifo_12_write,
        rxEng_headerMetaFifo_23_din,
        rxEng_headerMetaFifo_23_full_n,
        rxEng_headerMetaFifo_23_write,
        rxEng_headerMetaFifo_22_din,
        rxEng_headerMetaFifo_22_full_n,
        rxEng_headerMetaFifo_22_write,
        rxEng_headerMetaFifo_18_din,
        rxEng_headerMetaFifo_18_full_n,
        rxEng_headerMetaFifo_18_write,
        rxEng_headerMetaFifo_10_din,
        rxEng_headerMetaFifo_10_full_n,
        rxEng_headerMetaFifo_10_write,
        rxEng_headerMetaFifo_19_din,
        rxEng_headerMetaFifo_19_full_n,
        rxEng_headerMetaFifo_19_write,
        rxEng_headerMetaFifo_21_din,
        rxEng_headerMetaFifo_21_full_n,
        rxEng_headerMetaFifo_21_write,
        rxEng_headerMetaFifo_16_din,
        rxEng_headerMetaFifo_16_full_n,
        rxEng_headerMetaFifo_16_write,
        rxEng_headerMetaFifo_14_din,
        rxEng_headerMetaFifo_14_full_n,
        rxEng_headerMetaFifo_14_write,
        rxEng2portTable_chec_1_din,
        rxEng2portTable_chec_1_full_n,
        rxEng2portTable_chec_1_write,
        rxEng_tupleBuffer_V_din,
        rxEng_tupleBuffer_V_full_n,
        rxEng_tupleBuffer_V_write,
        rxEng_optionalFields_4_din,
        rxEng_optionalFields_4_full_n,
        rxEng_optionalFields_4_write,
        rxEng_optionalFields_5_din,
        rxEng_optionalFields_5_full_n,
        rxEng_optionalFields_5_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [576:0] rxEng_dataBuffer2_V_dout;
input   rxEng_dataBuffer2_V_empty_n;
output   rxEng_dataBuffer2_V_read;
input  [0:0] rxEng_checksumValidF_1_dout;
input   rxEng_checksumValidF_1_empty_n;
output   rxEng_checksumValidF_1_read;
output  [576:0] rxEng_dataBuffer3a_V_din;
input   rxEng_dataBuffer3a_V_full_n;
output   rxEng_dataBuffer3a_V_write;
output  [31:0] rxEng_headerMetaFifo_20_din;
input   rxEng_headerMetaFifo_20_full_n;
output   rxEng_headerMetaFifo_20_write;
output  [31:0] rxEng_headerMetaFifo_12_din;
input   rxEng_headerMetaFifo_12_full_n;
output   rxEng_headerMetaFifo_12_write;
output  [15:0] rxEng_headerMetaFifo_23_din;
input   rxEng_headerMetaFifo_23_full_n;
output   rxEng_headerMetaFifo_23_write;
output  [3:0] rxEng_headerMetaFifo_22_din;
input   rxEng_headerMetaFifo_22_full_n;
output   rxEng_headerMetaFifo_22_write;
output  [15:0] rxEng_headerMetaFifo_18_din;
input   rxEng_headerMetaFifo_18_full_n;
output   rxEng_headerMetaFifo_18_write;
output  [0:0] rxEng_headerMetaFifo_10_din;
input   rxEng_headerMetaFifo_10_full_n;
output   rxEng_headerMetaFifo_10_write;
output  [0:0] rxEng_headerMetaFifo_19_din;
input   rxEng_headerMetaFifo_19_full_n;
output   rxEng_headerMetaFifo_19_write;
output  [0:0] rxEng_headerMetaFifo_21_din;
input   rxEng_headerMetaFifo_21_full_n;
output   rxEng_headerMetaFifo_21_write;
output  [0:0] rxEng_headerMetaFifo_16_din;
input   rxEng_headerMetaFifo_16_full_n;
output   rxEng_headerMetaFifo_16_write;
output  [3:0] rxEng_headerMetaFifo_14_din;
input   rxEng_headerMetaFifo_14_full_n;
output   rxEng_headerMetaFifo_14_write;
output  [15:0] rxEng2portTable_chec_1_din;
input   rxEng2portTable_chec_1_full_n;
output   rxEng2portTable_chec_1_write;
output  [95:0] rxEng_tupleBuffer_V_din;
input   rxEng_tupleBuffer_V_full_n;
output   rxEng_tupleBuffer_V_write;
output  [3:0] rxEng_optionalFields_4_din;
input   rxEng_optionalFields_4_full_n;
output   rxEng_optionalFields_4_write;
output  [0:0] rxEng_optionalFields_5_din;
input   rxEng_optionalFields_5_full_n;
output   rxEng_optionalFields_5_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg rxEng_dataBuffer2_V_read;
reg rxEng_checksumValidF_1_read;
reg rxEng_dataBuffer3a_V_write;
reg rxEng_headerMetaFifo_20_write;
reg rxEng_headerMetaFifo_12_write;
reg rxEng_headerMetaFifo_23_write;
reg rxEng_headerMetaFifo_22_write;
reg rxEng_headerMetaFifo_18_write;
reg rxEng_headerMetaFifo_10_write;
reg rxEng_headerMetaFifo_19_write;
reg rxEng_headerMetaFifo_21_write;
reg rxEng_headerMetaFifo_16_write;
reg rxEng_headerMetaFifo_14_write;
reg rxEng2portTable_chec_1_write;
reg rxEng_tupleBuffer_V_write;
reg rxEng_optionalFields_4_write;
reg rxEng_optionalFields_5_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire   [0:0] tmp_nbreadreq_fu_204_p3;
wire   [0:0] tmp_5_nbreadreq_fu_212_p3;
reg    ap_predicate_op10_read_state1;
reg    ap_predicate_op36_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] tmp_reg_917;
reg   [0:0] tmp_reg_917_pp0_iter1_reg;
reg   [0:0] tmp_5_reg_925;
reg   [0:0] tmp_5_reg_925_pp0_iter1_reg;
reg   [0:0] or_ln73_reg_960;
reg   [0:0] pkgValid_loc_0_i_reg_333;
reg   [0:0] or_ln457_reg_968;
reg   [0:0] firstWord_load_reg_921;
reg   [0:0] firstWord_load_reg_921_pp0_iter1_reg;
reg    ap_predicate_op117_write_state3;
wire    io_acc_block_signal_op122;
reg   [0:0] metaWritten_1_load_reg_964;
reg    ap_predicate_op122_write_state3;
reg    ap_predicate_op123_write_state3;
reg    ap_predicate_op125_write_state3;
wire    io_acc_block_signal_op127;
reg   [0:0] or_ln478_reg_1069;
reg    ap_predicate_op127_write_state3;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] firstWord;
reg   [0:0] header_ready_1;
reg   [15:0] header_idx_6;
reg   [255:0] header_header_V_5;
reg   [0:0] pkgValid;
reg   [0:0] metaWritten_1;
reg    rxEng_dataBuffer2_V_blk_n;
wire    ap_block_pp0_stage0;
reg    rxEng_checksumValidF_1_blk_n;
reg    rxEng_dataBuffer3a_V_blk_n;
reg    rxEng_headerMetaFifo_20_blk_n;
reg    rxEng_headerMetaFifo_12_blk_n;
reg    rxEng_headerMetaFifo_23_blk_n;
reg    rxEng_headerMetaFifo_22_blk_n;
reg    rxEng_headerMetaFifo_18_blk_n;
reg    rxEng_headerMetaFifo_10_blk_n;
reg    rxEng_headerMetaFifo_19_blk_n;
reg    rxEng_headerMetaFifo_21_blk_n;
reg    rxEng_headerMetaFifo_16_blk_n;
reg    rxEng_headerMetaFifo_14_blk_n;
reg    rxEng2portTable_chec_1_blk_n;
reg    rxEng_tupleBuffer_V_blk_n;
reg    rxEng_optionalFields_4_blk_n;
reg    rxEng_optionalFields_5_blk_n;
reg   [576:0] tmp_1_reg_929;
reg   [576:0] tmp_1_reg_929_pp0_iter1_reg;
wire   [0:0] header_ready_1_load_load_fu_363_p1;
reg   [0:0] header_ready_1_load_reg_935;
wire   [15:0] add_ln67_fu_487_p2;
wire   [0:0] or_ln73_fu_503_p2;
wire   [0:0] metaWritten_1_load_load_fu_508_p1;
wire   [0:0] or_ln457_fu_578_p2;
wire   [0:0] ap_phi_mux_pkgValid_loc_0_i_phi_fu_336_p4;
reg   [7:0] p_Result_136_i_i_i_reg_972;
reg   [7:0] p_Result_136_1_i_i_reg_977;
reg   [7:0] p_Result_136_2_i_i_reg_982;
reg   [7:0] p_Result_136_3_i_i_reg_987;
reg   [7:0] p_Result_136_i_i_reg_992;
reg   [7:0] p_Result_136_1_i_i_2_reg_997;
reg   [7:0] p_Result_136_2_i_i_2_reg_1002;
reg   [7:0] p_Result_136_3_i_i_2_reg_1007;
reg   [7:0] p_Result_138_i_i_reg_1012;
reg   [7:0] p_Result_138_1_i_i_2_reg_1017;
wire   [3:0] meta_dataOffset_V_1_fu_716_p4;
reg   [3:0] meta_dataOffset_V_1_reg_1022;
wire   [15:0] meta_length_V_1_fu_738_p2;
reg   [15:0] meta_length_V_1_reg_1028;
reg   [0:0] p_Result_75_reg_1033;
reg   [0:0] p_Result_76_reg_1038;
reg   [0:0] p_Result_77_reg_1043;
reg   [0:0] p_Result_78_reg_1049;
reg   [15:0] tmp_V_reg_1054;
reg   [31:0] tmp_s_reg_1059;
wire   [63:0] trunc_ln181_fu_796_p1;
reg   [63:0] trunc_ln181_reg_1064;
wire   [0:0] or_ln478_fu_812_p2;
wire   [0:0] tmp_400_fu_818_p3;
reg   [0:0] tmp_400_reg_1073;
wire   [0:0] or_ln492_fu_825_p2;
wire   [0:0] xor_ln492_fu_831_p2;
reg   [0:0] xor_ln492_reg_1082;
reg    ap_block_pp0_stage0_subdone;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln73_reg_298;
reg   [15:0] ap_phi_reg_pp0_iter1_phi_ln73_reg_298;
wire   [0:0] ap_phi_reg_pp0_iter0_write_flag_1_i_i_reg_307;
reg   [0:0] ap_phi_reg_pp0_iter1_write_flag_1_i_i_reg_307;
wire   [0:0] ap_phi_reg_pp0_iter0_firstWord_flag_0_i_reg_320;
reg   [0:0] ap_phi_reg_pp0_iter1_firstWord_flag_0_i_reg_320;
wire   [0:0] ap_phi_reg_pp0_iter0_pkgValid_loc_0_i_reg_333;
reg   [0:0] ap_phi_reg_pp0_iter1_pkgValid_loc_0_i_reg_333;
wire   [0:0] ap_phi_reg_pp0_iter0_metaWritten_1_flag_1_reg_343;
reg   [0:0] ap_phi_reg_pp0_iter1_metaWritten_1_flag_1_reg_343;
reg   [0:0] ap_phi_reg_pp0_iter2_metaWritten_1_flag_1_reg_343;
reg   [0:0] ap_sig_allocacmp_firstWord_load;
wire   [0:0] and_ln492_fu_837_p2;
reg   [0:0] ap_sig_allocacmp_header_ready_1_load;
wire   [15:0] select_ln492_fu_843_p3;
reg   [15:0] ap_sig_allocacmp_header_idx_6_load;
wire   [255:0] p_Result_s_fu_475_p2;
wire   [0:0] or_ln492_1_fu_907_p2;
reg   [0:0] ap_sig_allocacmp_metaWritten_1_load;
reg    ap_block_pp0_stage0_01001;
wire   [16:0] tmp_393_fu_379_p3;
wire   [23:0] zext_ln414_fu_387_p1;
wire   [0:0] trunc_ln414_fu_397_p1;
wire   [0:0] icmp_ln414_fu_391_p2;
wire   [255:0] st_fu_401_p3;
wire   [255:0] tmp_V_13_fu_371_p1;
wire   [255:0] select_ln414_fu_409_p3;
reg   [255:0] tmp_394_fu_417_p4;
wire   [255:0] select_ln414_19_fu_435_p3;
wire   [255:0] select_ln414_20_fu_443_p3;
wire   [255:0] and_ln414_fu_451_p2;
wire   [255:0] xor_ln414_fu_457_p2;
wire   [255:0] select_ln414_18_fu_427_p3;
wire   [255:0] and_ln414_22_fu_463_p2;
wire   [255:0] and_ln414_23_fu_469_p2;
wire   [7:0] p_Result_138_1_i_i_fu_526_p4;
wire   [7:0] p_Result_138_i_i_i_fu_516_p4;
wire   [3:0] p_Result_i183_i_fu_544_p4;
wire   [5:0] ret_V_fu_554_p3;
wire   [15:0] agg_result_V_0_1_i_i_fu_536_p3;
wire   [15:0] zext_ln215_7_fu_562_p1;
wire   [0:0] icmp_ln457_fu_566_p2;
wire   [0:0] icmp_ln895_fu_572_p2;
wire   [7:0] p_Result_138_1_i_i_3_fu_698_p4;
wire   [7:0] p_Result_138_i_i1_fu_688_p4;
wire   [5:0] shl_ln_fu_726_p3;
wire   [15:0] agg_result_V_0_1_i_i_1_fu_708_p3;
wire   [15:0] zext_ln214_37_fu_734_p1;
wire   [0:0] icmp_ln478_fu_800_p2;
wire   [0:0] icmp_ln895_4_fu_806_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_62;
reg    ap_condition_204;
reg    ap_condition_365;
reg    ap_condition_275;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 firstWord = 1'd1;
#0 header_ready_1 = 1'd0;
#0 header_idx_6 = 16'd0;
#0 header_header_V_5 = 256'd28334198897217871282176;
#0 pkgValid = 1'd0;
#0 metaWritten_1 = 1'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_204)) begin
        if (((ap_sig_allocacmp_firstWord_load == 1'd0) & (tmp_nbreadreq_fu_204_p3 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_firstWord_flag_0_i_reg_320 <= 1'd0;
        end else if ((1'b1 == ap_condition_62)) begin
            ap_phi_reg_pp0_iter1_firstWord_flag_0_i_reg_320 <= 1'd1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_firstWord_flag_0_i_reg_320 <= ap_phi_reg_pp0_iter0_firstWord_flag_0_i_reg_320;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_204)) begin
        if ((1'b1 == ap_condition_275)) begin
            ap_phi_reg_pp0_iter1_phi_ln73_reg_298 <= add_ln67_fu_487_p2;
        end else if ((1'b1 == ap_condition_365)) begin
            ap_phi_reg_pp0_iter1_phi_ln73_reg_298 <= ap_sig_allocacmp_header_idx_6_load;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln73_reg_298 <= ap_phi_reg_pp0_iter0_phi_ln73_reg_298;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_204)) begin
        if (((ap_sig_allocacmp_firstWord_load == 1'd0) & (tmp_nbreadreq_fu_204_p3 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_pkgValid_loc_0_i_reg_333 <= pkgValid;
        end else if ((1'b1 == ap_condition_62)) begin
            ap_phi_reg_pp0_iter1_pkgValid_loc_0_i_reg_333 <= rxEng_checksumValidF_1_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_pkgValid_loc_0_i_reg_333 <= ap_phi_reg_pp0_iter0_pkgValid_loc_0_i_reg_333;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_204)) begin
        if ((1'b1 == ap_condition_275)) begin
            ap_phi_reg_pp0_iter1_write_flag_1_i_i_reg_307 <= 1'd1;
        end else if ((1'b1 == ap_condition_365)) begin
            ap_phi_reg_pp0_iter1_write_flag_1_i_i_reg_307 <= 1'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_write_flag_1_i_i_reg_307 <= ap_phi_reg_pp0_iter0_write_flag_1_i_i_reg_307;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((firstWord_load_reg_921 == 1'd0) & (metaWritten_1_load_load_fu_508_p1 == 1'd0) & (tmp_reg_917 == 1'd1) & (or_ln73_fu_503_p2 == 1'd1)) | ((metaWritten_1_load_load_fu_508_p1 == 1'd0) & (tmp_5_reg_925 == 1'd1) & (tmp_reg_917 == 1'd1) & (or_ln73_fu_503_p2 == 1'd1))))) begin
        ap_phi_reg_pp0_iter2_metaWritten_1_flag_1_reg_343 <= 1'd1;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((firstWord_load_reg_921 == 1'd0) & (tmp_reg_917 == 1'd1) & (metaWritten_1_load_load_fu_508_p1 == 1'd1) & (or_ln73_fu_503_p2 == 1'd1)) | ((tmp_5_reg_925 == 1'd1) & (tmp_reg_917 == 1'd1) & (metaWritten_1_load_load_fu_508_p1 == 1'd1) & (or_ln73_fu_503_p2 == 1'd1)))) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((firstWord_load_reg_921 == 1'd0) & (or_ln73_fu_503_p2 == 1'd0) & (tmp_reg_917 == 1'd1)) | ((or_ln73_fu_503_p2 == 1'd0) & (tmp_5_reg_925 == 1'd1) & (tmp_reg_917 == 1'd1)))))) begin
        ap_phi_reg_pp0_iter2_metaWritten_1_flag_1_reg_343 <= 1'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_metaWritten_1_flag_1_reg_343 <= ap_phi_reg_pp0_iter1_metaWritten_1_flag_1_reg_343;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_metaWritten_1_flag_1_reg_343 <= ap_phi_reg_pp0_iter0_metaWritten_1_flag_1_reg_343;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((firstWord_load_reg_921 == 1'd0) & (tmp_reg_917 == 1'd1) & (or_ln492_fu_825_p2 == 1'd1)) | ((tmp_5_reg_925 == 1'd1) & (tmp_reg_917 == 1'd1) & (or_ln492_fu_825_p2 == 1'd1))))) begin
        firstWord <= tmp_1_reg_929[32'd576];
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_nbreadreq_fu_204_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstWord_load_reg_921 <= ap_sig_allocacmp_firstWord_load;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstWord_load_reg_921_pp0_iter1_reg <= firstWord_load_reg_921;
        tmp_1_reg_929_pp0_iter1_reg <= tmp_1_reg_929;
        tmp_5_reg_925_pp0_iter1_reg <= tmp_5_reg_925;
        tmp_reg_917 <= tmp_nbreadreq_fu_204_p3;
        tmp_reg_917_pp0_iter1_reg <= tmp_reg_917;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((header_ready_1_load_load_fu_363_p1 == 1'd0) & (ap_sig_allocacmp_firstWord_load == 1'd0) & (tmp_nbreadreq_fu_204_p3 == 1'd1)) | ((header_ready_1_load_load_fu_363_p1 == 1'd0) & (tmp_5_nbreadreq_fu_212_p3 == 1'd1) & (tmp_nbreadreq_fu_204_p3 == 1'd1))))) begin
        header_header_V_5 <= p_Result_s_fu_475_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((firstWord_load_reg_921 == 1'd0) & (tmp_reg_917 == 1'd1)) | ((tmp_5_reg_925 == 1'd1) & (tmp_reg_917 == 1'd1))))) begin
        header_idx_6 <= select_ln492_fu_843_p3;
        header_ready_1 <= and_ln492_fu_837_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((ap_sig_allocacmp_firstWord_load == 1'd0) & (tmp_nbreadreq_fu_204_p3 == 1'd1)) | ((tmp_5_nbreadreq_fu_212_p3 == 1'd1) & (tmp_nbreadreq_fu_204_p3 == 1'd1))))) begin
        header_ready_1_load_reg_935 <= ap_sig_allocacmp_header_ready_1_load;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (((firstWord_load_reg_921_pp0_iter1_reg == 1'd0) & (tmp_reg_917_pp0_iter1_reg == 1'd1) & (or_ln492_1_fu_907_p2 == 1'd1)) | ((tmp_5_reg_925_pp0_iter1_reg == 1'd1) & (tmp_reg_917_pp0_iter1_reg == 1'd1) & (or_ln492_1_fu_907_p2 == 1'd1))))) begin
        metaWritten_1 <= xor_ln492_reg_1082;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((firstWord_load_reg_921 == 1'd0) & (tmp_reg_917 == 1'd1)) | ((tmp_5_reg_925 == 1'd1) & (tmp_reg_917 == 1'd1))))) begin
        metaWritten_1_load_reg_964 <= ap_sig_allocacmp_metaWritten_1_load;
        or_ln73_reg_960 <= or_ln73_fu_503_p2;
        tmp_400_reg_1073 <= tmp_1_reg_929[32'd576];
        xor_ln492_reg_1082 <= xor_ln492_fu_831_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((firstWord_load_reg_921 == 1'd0) & (metaWritten_1_load_load_fu_508_p1 == 1'd0) & (tmp_reg_917 == 1'd1) & (or_ln73_fu_503_p2 == 1'd1)) | ((metaWritten_1_load_load_fu_508_p1 == 1'd0) & (tmp_5_reg_925 == 1'd1) & (tmp_reg_917 == 1'd1) & (or_ln73_fu_503_p2 == 1'd1))))) begin
        meta_dataOffset_V_1_reg_1022 <= {{header_header_V_5[199:196]}};
        meta_length_V_1_reg_1028 <= meta_length_V_1_fu_738_p2;
        p_Result_136_1_i_i_2_reg_997 <= {{header_header_V_5[183:176]}};
        p_Result_136_1_i_i_reg_977 <= {{header_header_V_5[151:144]}};
        p_Result_136_2_i_i_2_reg_1002 <= {{header_header_V_5[175:168]}};
        p_Result_136_2_i_i_reg_982 <= {{header_header_V_5[143:136]}};
        p_Result_136_3_i_i_2_reg_1007 <= {{header_header_V_5[167:160]}};
        p_Result_136_3_i_i_reg_987 <= {{header_header_V_5[135:128]}};
        p_Result_136_i_i_i_reg_972 <= {{header_header_V_5[159:152]}};
        p_Result_136_i_i_reg_992 <= {{header_header_V_5[191:184]}};
        p_Result_138_1_i_i_2_reg_1017 <= {{header_header_V_5[215:208]}};
        p_Result_138_i_i_reg_1012 <= {{header_header_V_5[223:216]}};
        p_Result_75_reg_1033 <= header_header_V_5[32'd204];
        p_Result_76_reg_1038 <= header_header_V_5[32'd202];
        p_Result_77_reg_1043 <= header_header_V_5[32'd201];
        p_Result_78_reg_1049 <= header_header_V_5[32'd200];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((firstWord_load_reg_921 == 1'd0) & (tmp_reg_917 == 1'd1) & (ap_phi_mux_pkgValid_loc_0_i_phi_fu_336_p4 == 1'd1) & (or_ln73_fu_503_p2 == 1'd1)) | ((tmp_5_reg_925 == 1'd1) & (tmp_reg_917 == 1'd1) & (ap_phi_mux_pkgValid_loc_0_i_phi_fu_336_p4 == 1'd1) & (or_ln73_fu_503_p2 == 1'd1))))) begin
        or_ln457_reg_968 <= or_ln457_fu_578_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((firstWord_load_reg_921 == 1'd0) & (metaWritten_1_load_load_fu_508_p1 == 1'd0) & (tmp_reg_917 == 1'd1) & (ap_phi_mux_pkgValid_loc_0_i_phi_fu_336_p4 == 1'd1) & (or_ln73_fu_503_p2 == 1'd1)) | ((metaWritten_1_load_load_fu_508_p1 == 1'd0) & (tmp_5_reg_925 == 1'd1) & (tmp_reg_917 == 1'd1) & (ap_phi_mux_pkgValid_loc_0_i_phi_fu_336_p4 == 1'd1) & (or_ln73_fu_503_p2 == 1'd1))))) begin
        or_ln478_reg_1069 <= or_ln478_fu_812_p2;
        tmp_V_reg_1054 <= {{header_header_V_5[127:112]}};
        tmp_s_reg_1059 <= {{header_header_V_5[127:96]}};
        trunc_ln181_reg_1064 <= trunc_ln181_fu_796_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sig_allocacmp_firstWord_load == 1'd1) & (tmp_5_nbreadreq_fu_212_p3 == 1'd1) & (tmp_nbreadreq_fu_204_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pkgValid <= rxEng_checksumValidF_1_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pkgValid_loc_0_i_reg_333 <= ap_phi_reg_pp0_iter1_pkgValid_loc_0_i_reg_333;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op10_read_state1 == 1'b1))) begin
        tmp_1_reg_929 <= rxEng_dataBuffer2_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sig_allocacmp_firstWord_load == 1'd1) & (tmp_nbreadreq_fu_204_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_5_reg_925 <= tmp_5_nbreadreq_fu_212_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((firstWord_load_reg_921 == 1'd0) & (tmp_reg_917 == 1'd1) & (or_ln492_fu_825_p2 == 1'd1)) | ((tmp_5_reg_925 == 1'd1) & (tmp_reg_917 == 1'd1) & (or_ln492_fu_825_p2 == 1'd1))))) begin
        ap_sig_allocacmp_firstWord_load = tmp_1_reg_929[32'd576];
    end else begin
        ap_sig_allocacmp_firstWord_load = firstWord;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((firstWord_load_reg_921 == 1'd0) & (tmp_reg_917 == 1'd1)) | ((tmp_5_reg_925 == 1'd1) & (tmp_reg_917 == 1'd1))))) begin
        ap_sig_allocacmp_header_idx_6_load = select_ln492_fu_843_p3;
    end else begin
        ap_sig_allocacmp_header_idx_6_load = header_idx_6;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((firstWord_load_reg_921 == 1'd0) & (tmp_reg_917 == 1'd1)) | ((tmp_5_reg_925 == 1'd1) & (tmp_reg_917 == 1'd1))))) begin
        ap_sig_allocacmp_header_ready_1_load = and_ln492_fu_837_p2;
    end else begin
        ap_sig_allocacmp_header_ready_1_load = header_ready_1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (((firstWord_load_reg_921_pp0_iter1_reg == 1'd0) & (tmp_reg_917_pp0_iter1_reg == 1'd1) & (or_ln492_1_fu_907_p2 == 1'd1)) | ((tmp_5_reg_925_pp0_iter1_reg == 1'd1) & (tmp_reg_917_pp0_iter1_reg == 1'd1) & (or_ln492_1_fu_907_p2 == 1'd1))))) begin
        ap_sig_allocacmp_metaWritten_1_load = xor_ln492_reg_1082;
    end else begin
        ap_sig_allocacmp_metaWritten_1_load = metaWritten_1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op123_write_state3 == 1'b1))) begin
        rxEng2portTable_chec_1_blk_n = rxEng2portTable_chec_1_full_n;
    end else begin
        rxEng2portTable_chec_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op123_write_state3 == 1'b1))) begin
        rxEng2portTable_chec_1_write = 1'b1;
    end else begin
        rxEng2portTable_chec_1_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op36_read_state1 == 1'b1))) begin
        rxEng_checksumValidF_1_blk_n = rxEng_checksumValidF_1_empty_n;
    end else begin
        rxEng_checksumValidF_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op36_read_state1 == 1'b1))) begin
        rxEng_checksumValidF_1_read = 1'b1;
    end else begin
        rxEng_checksumValidF_1_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op10_read_state1 == 1'b1))) begin
        rxEng_dataBuffer2_V_blk_n = rxEng_dataBuffer2_V_empty_n;
    end else begin
        rxEng_dataBuffer2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op10_read_state1 == 1'b1))) begin
        rxEng_dataBuffer2_V_read = 1'b1;
    end else begin
        rxEng_dataBuffer2_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op117_write_state3 == 1'b1))) begin
        rxEng_dataBuffer3a_V_blk_n = rxEng_dataBuffer3a_V_full_n;
    end else begin
        rxEng_dataBuffer3a_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op117_write_state3 == 1'b1))) begin
        rxEng_dataBuffer3a_V_write = 1'b1;
    end else begin
        rxEng_dataBuffer3a_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op122_write_state3 == 1'b1))) begin
        rxEng_headerMetaFifo_10_blk_n = rxEng_headerMetaFifo_10_full_n;
    end else begin
        rxEng_headerMetaFifo_10_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op122_write_state3 == 1'b1))) begin
        rxEng_headerMetaFifo_10_write = 1'b1;
    end else begin
        rxEng_headerMetaFifo_10_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op122_write_state3 == 1'b1))) begin
        rxEng_headerMetaFifo_12_blk_n = rxEng_headerMetaFifo_12_full_n;
    end else begin
        rxEng_headerMetaFifo_12_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op122_write_state3 == 1'b1))) begin
        rxEng_headerMetaFifo_12_write = 1'b1;
    end else begin
        rxEng_headerMetaFifo_12_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op122_write_state3 == 1'b1))) begin
        rxEng_headerMetaFifo_14_blk_n = rxEng_headerMetaFifo_14_full_n;
    end else begin
        rxEng_headerMetaFifo_14_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op122_write_state3 == 1'b1))) begin
        rxEng_headerMetaFifo_14_write = 1'b1;
    end else begin
        rxEng_headerMetaFifo_14_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op122_write_state3 == 1'b1))) begin
        rxEng_headerMetaFifo_16_blk_n = rxEng_headerMetaFifo_16_full_n;
    end else begin
        rxEng_headerMetaFifo_16_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op122_write_state3 == 1'b1))) begin
        rxEng_headerMetaFifo_16_write = 1'b1;
    end else begin
        rxEng_headerMetaFifo_16_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op122_write_state3 == 1'b1))) begin
        rxEng_headerMetaFifo_18_blk_n = rxEng_headerMetaFifo_18_full_n;
    end else begin
        rxEng_headerMetaFifo_18_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op122_write_state3 == 1'b1))) begin
        rxEng_headerMetaFifo_18_write = 1'b1;
    end else begin
        rxEng_headerMetaFifo_18_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op122_write_state3 == 1'b1))) begin
        rxEng_headerMetaFifo_19_blk_n = rxEng_headerMetaFifo_19_full_n;
    end else begin
        rxEng_headerMetaFifo_19_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op122_write_state3 == 1'b1))) begin
        rxEng_headerMetaFifo_19_write = 1'b1;
    end else begin
        rxEng_headerMetaFifo_19_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op122_write_state3 == 1'b1))) begin
        rxEng_headerMetaFifo_20_blk_n = rxEng_headerMetaFifo_20_full_n;
    end else begin
        rxEng_headerMetaFifo_20_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op122_write_state3 == 1'b1))) begin
        rxEng_headerMetaFifo_20_write = 1'b1;
    end else begin
        rxEng_headerMetaFifo_20_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op122_write_state3 == 1'b1))) begin
        rxEng_headerMetaFifo_21_blk_n = rxEng_headerMetaFifo_21_full_n;
    end else begin
        rxEng_headerMetaFifo_21_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op122_write_state3 == 1'b1))) begin
        rxEng_headerMetaFifo_21_write = 1'b1;
    end else begin
        rxEng_headerMetaFifo_21_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op122_write_state3 == 1'b1))) begin
        rxEng_headerMetaFifo_22_blk_n = rxEng_headerMetaFifo_22_full_n;
    end else begin
        rxEng_headerMetaFifo_22_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op122_write_state3 == 1'b1))) begin
        rxEng_headerMetaFifo_22_write = 1'b1;
    end else begin
        rxEng_headerMetaFifo_22_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op122_write_state3 == 1'b1))) begin
        rxEng_headerMetaFifo_23_blk_n = rxEng_headerMetaFifo_23_full_n;
    end else begin
        rxEng_headerMetaFifo_23_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op122_write_state3 == 1'b1))) begin
        rxEng_headerMetaFifo_23_write = 1'b1;
    end else begin
        rxEng_headerMetaFifo_23_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op127_write_state3 == 1'b1))) begin
        rxEng_optionalFields_4_blk_n = rxEng_optionalFields_4_full_n;
    end else begin
        rxEng_optionalFields_4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op127_write_state3 == 1'b1))) begin
        rxEng_optionalFields_4_write = 1'b1;
    end else begin
        rxEng_optionalFields_4_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op127_write_state3 == 1'b1))) begin
        rxEng_optionalFields_5_blk_n = rxEng_optionalFields_5_full_n;
    end else begin
        rxEng_optionalFields_5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op127_write_state3 == 1'b1))) begin
        rxEng_optionalFields_5_write = 1'b1;
    end else begin
        rxEng_optionalFields_5_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op125_write_state3 == 1'b1))) begin
        rxEng_tupleBuffer_V_blk_n = rxEng_tupleBuffer_V_full_n;
    end else begin
        rxEng_tupleBuffer_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op125_write_state3 == 1'b1))) begin
        rxEng_tupleBuffer_V_write = 1'b1;
    end else begin
        rxEng_tupleBuffer_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln67_fu_487_p2 = (16'd1 + ap_sig_allocacmp_header_idx_6_load);

assign agg_result_V_0_1_i_i_1_fu_708_p3 = {{p_Result_138_1_i_i_3_fu_698_p4}, {p_Result_138_i_i1_fu_688_p4}};

assign agg_result_V_0_1_i_i_fu_536_p3 = {{p_Result_138_1_i_i_fu_526_p4}, {p_Result_138_i_i_i_fu_516_p4}};

assign and_ln414_22_fu_463_p2 = (xor_ln414_fu_457_p2 & header_header_V_5);

assign and_ln414_23_fu_469_p2 = (select_ln414_18_fu_427_p3 & and_ln414_fu_451_p2);

assign and_ln414_fu_451_p2 = (select_ln414_20_fu_443_p3 & select_ln414_19_fu_435_p3);

assign and_ln492_fu_837_p2 = (xor_ln492_fu_831_p2 & or_ln73_fu_503_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((rxEng_checksumValidF_1_empty_n == 1'b0) & (ap_predicate_op36_read_state1 == 1'b1)) | ((rxEng_dataBuffer2_V_empty_n == 1'b0) & (ap_predicate_op10_read_state1 == 1'b1)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((rxEng_dataBuffer3a_V_full_n == 1'b0) & (ap_predicate_op117_write_state3 == 1'b1)) | ((io_acc_block_signal_op127 == 1'b0) & (ap_predicate_op127_write_state3 == 1'b1)) | ((rxEng_tupleBuffer_V_full_n == 1'b0) & (ap_predicate_op125_write_state3 == 1'b1)) | ((rxEng2portTable_chec_1_full_n == 1'b0) & (ap_predicate_op123_write_state3 == 1'b1)) | ((io_acc_block_signal_op122 == 1'b0) & (ap_predicate_op122_write_state3 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((rxEng_checksumValidF_1_empty_n == 1'b0) & (ap_predicate_op36_read_state1 == 1'b1)) | ((rxEng_dataBuffer2_V_empty_n == 1'b0) & (ap_predicate_op10_read_state1 == 1'b1)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((rxEng_dataBuffer3a_V_full_n == 1'b0) & (ap_predicate_op117_write_state3 == 1'b1)) | ((io_acc_block_signal_op127 == 1'b0) & (ap_predicate_op127_write_state3 == 1'b1)) | ((rxEng_tupleBuffer_V_full_n == 1'b0) & (ap_predicate_op125_write_state3 == 1'b1)) | ((rxEng2portTable_chec_1_full_n == 1'b0) & (ap_predicate_op123_write_state3 == 1'b1)) | ((io_acc_block_signal_op122 == 1'b0) & (ap_predicate_op122_write_state3 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((rxEng_checksumValidF_1_empty_n == 1'b0) & (ap_predicate_op36_read_state1 == 1'b1)) | ((rxEng_dataBuffer2_V_empty_n == 1'b0) & (ap_predicate_op10_read_state1 == 1'b1)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((rxEng_dataBuffer3a_V_full_n == 1'b0) & (ap_predicate_op117_write_state3 == 1'b1)) | ((io_acc_block_signal_op127 == 1'b0) & (ap_predicate_op127_write_state3 == 1'b1)) | ((rxEng_tupleBuffer_V_full_n == 1'b0) & (ap_predicate_op125_write_state3 == 1'b1)) | ((rxEng2portTable_chec_1_full_n == 1'b0) & (ap_predicate_op123_write_state3 == 1'b1)) | ((io_acc_block_signal_op122 == 1'b0) & (ap_predicate_op122_write_state3 == 1'b1)))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((rxEng_checksumValidF_1_empty_n == 1'b0) & (ap_predicate_op36_read_state1 == 1'b1)) | ((rxEng_dataBuffer2_V_empty_n == 1'b0) & (ap_predicate_op10_read_state1 == 1'b1)));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (((rxEng_dataBuffer3a_V_full_n == 1'b0) & (ap_predicate_op117_write_state3 == 1'b1)) | ((io_acc_block_signal_op127 == 1'b0) & (ap_predicate_op127_write_state3 == 1'b1)) | ((rxEng_tupleBuffer_V_full_n == 1'b0) & (ap_predicate_op125_write_state3 == 1'b1)) | ((rxEng2portTable_chec_1_full_n == 1'b0) & (ap_predicate_op123_write_state3 == 1'b1)) | ((io_acc_block_signal_op122 == 1'b0) & (ap_predicate_op122_write_state3 == 1'b1)));
end

always @ (*) begin
    ap_condition_204 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_275 = (((header_ready_1_load_load_fu_363_p1 == 1'd0) & (ap_sig_allocacmp_firstWord_load == 1'd0) & (tmp_nbreadreq_fu_204_p3 == 1'd1)) | ((header_ready_1_load_load_fu_363_p1 == 1'd0) & (tmp_5_nbreadreq_fu_212_p3 == 1'd1) & (tmp_nbreadreq_fu_204_p3 == 1'd1)));
end

always @ (*) begin
    ap_condition_365 = (((ap_sig_allocacmp_firstWord_load == 1'd0) & (header_ready_1_load_load_fu_363_p1 == 1'd1) & (tmp_nbreadreq_fu_204_p3 == 1'd1)) | ((tmp_5_nbreadreq_fu_212_p3 == 1'd1) & (header_ready_1_load_load_fu_363_p1 == 1'd1) & (tmp_nbreadreq_fu_204_p3 == 1'd1)));
end

always @ (*) begin
    ap_condition_62 = ((ap_sig_allocacmp_firstWord_load == 1'd1) & (tmp_5_nbreadreq_fu_212_p3 == 1'd1) & (tmp_nbreadreq_fu_204_p3 == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_mux_pkgValid_loc_0_i_phi_fu_336_p4 = ap_phi_reg_pp0_iter1_pkgValid_loc_0_i_reg_333;

assign ap_phi_reg_pp0_iter0_firstWord_flag_0_i_reg_320 = 'bx;

assign ap_phi_reg_pp0_iter0_metaWritten_1_flag_1_reg_343 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln73_reg_298 = 'bx;

assign ap_phi_reg_pp0_iter0_pkgValid_loc_0_i_reg_333 = 'bx;

assign ap_phi_reg_pp0_iter0_write_flag_1_i_i_reg_307 = 'bx;

always @ (*) begin
    ap_predicate_op10_read_state1 = (((ap_sig_allocacmp_firstWord_load == 1'd0) & (tmp_nbreadreq_fu_204_p3 == 1'd1)) | ((tmp_5_nbreadreq_fu_212_p3 == 1'd1) & (tmp_nbreadreq_fu_204_p3 == 1'd1)));
end

always @ (*) begin
    ap_predicate_op117_write_state3 = (((firstWord_load_reg_921_pp0_iter1_reg == 1'd0) & (or_ln457_reg_968 == 1'd1) & (pkgValid_loc_0_i_reg_333 == 1'd1) & (or_ln73_reg_960 == 1'd1) & (tmp_reg_917_pp0_iter1_reg == 1'd1)) | ((or_ln457_reg_968 == 1'd1) & (pkgValid_loc_0_i_reg_333 == 1'd1) & (or_ln73_reg_960 == 1'd1) & (tmp_5_reg_925_pp0_iter1_reg == 1'd1) & (tmp_reg_917_pp0_iter1_reg == 1'd1)));
end

always @ (*) begin
    ap_predicate_op122_write_state3 = (((firstWord_load_reg_921_pp0_iter1_reg == 1'd0) & (metaWritten_1_load_reg_964 == 1'd0) & (pkgValid_loc_0_i_reg_333 == 1'd1) & (or_ln73_reg_960 == 1'd1) & (tmp_reg_917_pp0_iter1_reg == 1'd1)) | ((metaWritten_1_load_reg_964 == 1'd0) & (pkgValid_loc_0_i_reg_333 == 1'd1) & (or_ln73_reg_960 == 1'd1) & (tmp_5_reg_925_pp0_iter1_reg == 1'd1) & (tmp_reg_917_pp0_iter1_reg == 1'd1)));
end

always @ (*) begin
    ap_predicate_op123_write_state3 = (((firstWord_load_reg_921_pp0_iter1_reg == 1'd0) & (metaWritten_1_load_reg_964 == 1'd0) & (pkgValid_loc_0_i_reg_333 == 1'd1) & (or_ln73_reg_960 == 1'd1) & (tmp_reg_917_pp0_iter1_reg == 1'd1)) | ((metaWritten_1_load_reg_964 == 1'd0) & (pkgValid_loc_0_i_reg_333 == 1'd1) & (or_ln73_reg_960 == 1'd1) & (tmp_5_reg_925_pp0_iter1_reg == 1'd1) & (tmp_reg_917_pp0_iter1_reg == 1'd1)));
end

always @ (*) begin
    ap_predicate_op125_write_state3 = (((firstWord_load_reg_921_pp0_iter1_reg == 1'd0) & (metaWritten_1_load_reg_964 == 1'd0) & (pkgValid_loc_0_i_reg_333 == 1'd1) & (or_ln73_reg_960 == 1'd1) & (tmp_reg_917_pp0_iter1_reg == 1'd1)) | ((metaWritten_1_load_reg_964 == 1'd0) & (pkgValid_loc_0_i_reg_333 == 1'd1) & (or_ln73_reg_960 == 1'd1) & (tmp_5_reg_925_pp0_iter1_reg == 1'd1) & (tmp_reg_917_pp0_iter1_reg == 1'd1)));
end

always @ (*) begin
    ap_predicate_op127_write_state3 = (((firstWord_load_reg_921_pp0_iter1_reg == 1'd0) & (metaWritten_1_load_reg_964 == 1'd0) & (pkgValid_loc_0_i_reg_333 == 1'd1) & (or_ln73_reg_960 == 1'd1) & (tmp_reg_917_pp0_iter1_reg == 1'd1) & (or_ln478_reg_1069 == 1'd1)) | ((metaWritten_1_load_reg_964 == 1'd0) & (pkgValid_loc_0_i_reg_333 == 1'd1) & (or_ln73_reg_960 == 1'd1) & (tmp_5_reg_925_pp0_iter1_reg == 1'd1) & (tmp_reg_917_pp0_iter1_reg == 1'd1) & (or_ln478_reg_1069 == 1'd1)));
end

always @ (*) begin
    ap_predicate_op36_read_state1 = ((ap_sig_allocacmp_firstWord_load == 1'd1) & (tmp_5_nbreadreq_fu_212_p3 == 1'd1) & (tmp_nbreadreq_fu_204_p3 == 1'd1));
end

assign header_ready_1_load_load_fu_363_p1 = ap_sig_allocacmp_header_ready_1_load;

assign icmp_ln414_fu_391_p2 = ((zext_ln414_fu_387_p1 != 24'd0) ? 1'b1 : 1'b0);

assign icmp_ln457_fu_566_p2 = ((agg_result_V_0_1_i_i_fu_536_p3 != zext_ln215_7_fu_562_p1) ? 1'b1 : 1'b0);

assign icmp_ln478_fu_800_p2 = ((agg_result_V_0_1_i_i_1_fu_708_p3 != zext_ln214_37_fu_734_p1) ? 1'b1 : 1'b0);

assign icmp_ln895_4_fu_806_p2 = ((meta_dataOffset_V_1_fu_716_p4 > 4'd5) ? 1'b1 : 1'b0);

assign icmp_ln895_fu_572_p2 = ((p_Result_i183_i_fu_544_p4 > 4'd5) ? 1'b1 : 1'b0);

assign io_acc_block_signal_op122 = (rxEng_headerMetaFifo_23_full_n & rxEng_headerMetaFifo_22_full_n & rxEng_headerMetaFifo_21_full_n & rxEng_headerMetaFifo_20_full_n & rxEng_headerMetaFifo_19_full_n & rxEng_headerMetaFifo_18_full_n & rxEng_headerMetaFifo_16_full_n & rxEng_headerMetaFifo_14_full_n & rxEng_headerMetaFifo_12_full_n & rxEng_headerMetaFifo_10_full_n);

assign io_acc_block_signal_op127 = (rxEng_optionalFields_5_full_n & rxEng_optionalFields_4_full_n);

assign metaWritten_1_load_load_fu_508_p1 = ap_sig_allocacmp_metaWritten_1_load;

assign meta_dataOffset_V_1_fu_716_p4 = {{header_header_V_5[199:196]}};

assign meta_length_V_1_fu_738_p2 = (agg_result_V_0_1_i_i_1_fu_708_p3 - zext_ln214_37_fu_734_p1);

assign or_ln457_fu_578_p2 = (icmp_ln895_fu_572_p2 | icmp_ln457_fu_566_p2);

assign or_ln478_fu_812_p2 = (icmp_ln895_4_fu_806_p2 | icmp_ln478_fu_800_p2);

assign or_ln492_1_fu_907_p2 = (tmp_400_reg_1073 | ap_phi_reg_pp0_iter2_metaWritten_1_flag_1_reg_343);

assign or_ln492_fu_825_p2 = (tmp_400_fu_818_p3 | ap_phi_reg_pp0_iter1_firstWord_flag_0_i_reg_320);

assign or_ln73_fu_503_p2 = (header_ready_1_load_reg_935 | ap_phi_reg_pp0_iter1_write_flag_1_i_i_reg_307);

assign p_Result_138_1_i_i_3_fu_698_p4 = {{header_header_V_5[87:80]}};

assign p_Result_138_1_i_i_fu_526_p4 = {{header_header_V_5[87:80]}};

assign p_Result_138_i_i1_fu_688_p4 = {{header_header_V_5[95:88]}};

assign p_Result_138_i_i_i_fu_516_p4 = {{header_header_V_5[95:88]}};

assign p_Result_i183_i_fu_544_p4 = {{header_header_V_5[199:196]}};

assign p_Result_s_fu_475_p2 = (and_ln414_23_fu_469_p2 | and_ln414_22_fu_463_p2);

assign ret_V_fu_554_p3 = {{p_Result_i183_i_fu_544_p4}, {2'd0}};

assign rxEng2portTable_chec_1_din = tmp_V_reg_1054;

assign rxEng_dataBuffer3a_V_din = tmp_1_reg_929_pp0_iter1_reg;

assign rxEng_headerMetaFifo_10_din = p_Result_75_reg_1033;

assign rxEng_headerMetaFifo_12_din = {{{{p_Result_136_3_i_i_2_reg_1007}, {p_Result_136_2_i_i_2_reg_1002}}, {p_Result_136_1_i_i_2_reg_997}}, {p_Result_136_i_i_reg_992}};

assign rxEng_headerMetaFifo_14_din = meta_dataOffset_V_1_reg_1022;

assign rxEng_headerMetaFifo_16_din = p_Result_78_reg_1049;

assign rxEng_headerMetaFifo_18_din = meta_length_V_1_reg_1028;

assign rxEng_headerMetaFifo_19_din = p_Result_76_reg_1038;

assign rxEng_headerMetaFifo_20_din = {{{{p_Result_136_3_i_i_reg_987}, {p_Result_136_2_i_i_reg_982}}, {p_Result_136_1_i_i_reg_977}}, {p_Result_136_i_i_i_reg_972}};

assign rxEng_headerMetaFifo_21_din = p_Result_77_reg_1043;

assign rxEng_headerMetaFifo_22_din = 4'd0;

assign rxEng_headerMetaFifo_23_din = {{p_Result_138_1_i_i_2_reg_1017}, {p_Result_138_i_i_reg_1012}};

assign rxEng_optionalFields_4_din = ($signed(meta_dataOffset_V_1_reg_1022) + $signed(4'd11));

assign rxEng_optionalFields_5_din = p_Result_77_reg_1043;

assign rxEng_tupleBuffer_V_din = {{tmp_s_reg_1059}, {trunc_ln181_reg_1064}};

assign select_ln414_18_fu_427_p3 = ((icmp_ln414_fu_391_p2[0:0] === 1'b1) ? tmp_394_fu_417_p4 : tmp_V_13_fu_371_p1);

assign select_ln414_19_fu_435_p3 = ((icmp_ln414_fu_391_p2[0:0] === 1'b1) ? 256'd57896044618658097711785492504343953926634992332820282019728792003956564819968 : 256'd115792089237316195423570985008687907853269984665640564039457584007913129639935);

assign select_ln414_20_fu_443_p3 = ((icmp_ln414_fu_391_p2[0:0] === 1'b1) ? 256'd1 : 256'd115792089237316195423570985008687907853269984665640564039457584007913129639935);

assign select_ln414_fu_409_p3 = ((icmp_ln414_fu_391_p2[0:0] === 1'b1) ? st_fu_401_p3 : tmp_V_13_fu_371_p1);

assign select_ln492_fu_843_p3 = ((tmp_400_fu_818_p3[0:0] === 1'b1) ? 16'd0 : ap_phi_reg_pp0_iter1_phi_ln73_reg_298);

assign shl_ln_fu_726_p3 = {{meta_dataOffset_V_1_fu_716_p4}, {2'd0}};

assign st_fu_401_p3 = {{trunc_ln414_fu_397_p1}, {255'd0}};

assign tmp_393_fu_379_p3 = {{ap_sig_allocacmp_header_idx_6_load}, {1'd0}};

integer ap_tvar_int_0;

always @ (select_ln414_fu_409_p3) begin
    for (ap_tvar_int_0 = 256 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 255 - 0) begin
            tmp_394_fu_417_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            tmp_394_fu_417_p4[ap_tvar_int_0] = select_ln414_fu_409_p3[255 - ap_tvar_int_0];
        end
    end
end

assign tmp_400_fu_818_p3 = tmp_1_reg_929[32'd576];

assign tmp_5_nbreadreq_fu_212_p3 = rxEng_checksumValidF_1_empty_n;

assign tmp_V_13_fu_371_p1 = rxEng_dataBuffer2_V_dout[255:0];

assign tmp_nbreadreq_fu_204_p3 = rxEng_dataBuffer2_V_empty_n;

assign trunc_ln181_fu_796_p1 = header_header_V_5[63:0];

assign trunc_ln414_fu_397_p1 = rxEng_dataBuffer2_V_dout[0:0];

assign xor_ln414_fu_457_p2 = (256'd115792089237316195423570985008687907853269984665640564039457584007913129639935 ^ and_ln414_fu_451_p2);

assign xor_ln492_fu_831_p2 = (tmp_400_fu_818_p3 ^ 1'd1);

assign zext_ln214_37_fu_734_p1 = shl_ln_fu_726_p3;

assign zext_ln215_7_fu_562_p1 = ret_V_fu_554_p3;

assign zext_ln414_fu_387_p1 = tmp_393_fu_379_p3;

endmodule //processPseudoHeader
