// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mac_ip_encode_top,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcu280-fsvh2892-2L-e,HLS_INPUT_CLOCK=3.200000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.777250,HLS_SYN_LAT=17,HLS_SYN_TPT=1,HLS_SYN_MEM=165,HLS_SYN_DSP=0,HLS_SYN_FF=11179,HLS_SYN_LUT=13518,HLS_VERSION=2020_1}" *)

module mac_ip_encode_top (
        s_axis_ip_TDATA,
        s_axis_ip_TKEEP,
        s_axis_ip_TLAST,
        s_axis_arp_lookup_reply_V_TDATA,
        m_axis_ip_TDATA,
        m_axis_ip_TKEEP,
        m_axis_ip_TLAST,
        m_axis_arp_lookup_request_V_V_TDATA,
        myMacAddress_V,
        regSubNetMask_V,
        regDefaultGateway_V,
        ap_clk,
        ap_rst_n,
        s_axis_ip_TVALID,
        s_axis_ip_TREADY,
        m_axis_arp_lookup_request_V_V_TVALID,
        m_axis_arp_lookup_request_V_V_TREADY,
        s_axis_arp_lookup_reply_V_TVALID,
        s_axis_arp_lookup_reply_V_TREADY,
        m_axis_ip_TVALID,
        m_axis_ip_TREADY
);


input  [511:0] s_axis_ip_TDATA;
input  [63:0] s_axis_ip_TKEEP;
input  [0:0] s_axis_ip_TLAST;
input  [55:0] s_axis_arp_lookup_reply_V_TDATA;
output  [511:0] m_axis_ip_TDATA;
output  [63:0] m_axis_ip_TKEEP;
output  [0:0] m_axis_ip_TLAST;
output  [31:0] m_axis_arp_lookup_request_V_V_TDATA;
input  [47:0] myMacAddress_V;
input  [31:0] regSubNetMask_V;
input  [31:0] regDefaultGateway_V;
input   ap_clk;
input   ap_rst_n;
input   s_axis_ip_TVALID;
output   s_axis_ip_TREADY;
output   m_axis_arp_lookup_request_V_V_TVALID;
input   m_axis_arp_lookup_request_V_V_TREADY;
input   s_axis_arp_lookup_reply_V_TVALID;
output   s_axis_arp_lookup_reply_V_TREADY;
output   m_axis_ip_TVALID;
input   m_axis_ip_TREADY;

 reg    ap_rst_n_inv;
wire    extract_ip_address_U0_ap_start;
wire    extract_ip_address_U0_ap_done;
wire    extract_ip_address_U0_ap_continue;
wire    extract_ip_address_U0_ap_idle;
wire    extract_ip_address_U0_ap_ready;
wire   [576:0] extract_ip_address_U0_dataStreamBuffer0_V_din;
wire    extract_ip_address_U0_dataStreamBuffer0_V_write;
wire    extract_ip_address_U0_s_axis_ip_TREADY;
wire   [31:0] extract_ip_address_U0_arpTableOut_V_V_TDATA;
wire    extract_ip_address_U0_arpTableOut_V_V_TVALID;
wire    ap_sync_continue;
wire    mac_compute_ipv4_che_U0_ap_start;
wire    mac_compute_ipv4_che_U0_ap_done;
wire    mac_compute_ipv4_che_U0_ap_continue;
wire    mac_compute_ipv4_che_U0_ap_idle;
wire    mac_compute_ipv4_che_U0_ap_ready;
wire    mac_compute_ipv4_che_U0_dataStreamBuffer0_V_read;
wire   [576:0] mac_compute_ipv4_che_U0_dataStreamBuffer1_V_din;
wire    mac_compute_ipv4_che_U0_dataStreamBuffer1_V_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_0_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_0_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_1_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_1_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_2_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_2_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_3_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_3_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_4_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_4_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_5_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_5_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_6_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_6_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_7_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_7_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_8_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_8_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_9_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_9_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_10_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_10_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_11_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_11_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_12_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_12_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_13_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_13_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_14_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_14_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_15_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_15_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_16_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_16_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_17_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_17_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_18_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_18_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_19_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_19_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_20_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_20_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_21_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_21_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_22_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_22_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_23_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_23_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_24_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_24_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_25_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_25_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_26_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_26_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_27_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_27_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_28_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_28_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_29_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_29_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_30_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_30_write;
wire   [16:0] mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_31_din;
wire    mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_31_write;
wire    mac_finalize_ipv4_ch_U0_ap_start;
wire    mac_finalize_ipv4_ch_U0_ap_done;
wire    mac_finalize_ipv4_ch_U0_ap_continue;
wire    mac_finalize_ipv4_ch_U0_ap_idle;
wire    mac_finalize_ipv4_ch_U0_ap_ready;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_0_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_1_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_2_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_3_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_4_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_5_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_6_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_7_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_8_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_9_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_10_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_11_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_12_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_13_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_14_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_15_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_16_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_17_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_18_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_19_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_20_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_21_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_22_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_23_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_24_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_25_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_26_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_27_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_28_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_29_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_30_read;
wire    mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_31_read;
wire   [15:0] mac_finalize_ipv4_ch_U0_checksumFifo_V_V_din;
wire    mac_finalize_ipv4_ch_U0_checksumFifo_V_V_write;
wire    insert_ip_checksum_U0_ap_start;
wire    insert_ip_checksum_U0_ap_done;
wire    insert_ip_checksum_U0_ap_continue;
wire    insert_ip_checksum_U0_ap_idle;
wire    insert_ip_checksum_U0_ap_ready;
wire    insert_ip_checksum_U0_dataStreamBuffer1_V_read;
wire    insert_ip_checksum_U0_checksumFifo_V_V_read;
wire   [576:0] insert_ip_checksum_U0_dataStreamBuffer2_V_din;
wire    insert_ip_checksum_U0_dataStreamBuffer2_V_write;
wire    handle_arp_reply_U0_ap_start;
wire    handle_arp_reply_U0_ap_done;
wire    handle_arp_reply_U0_ap_continue;
wire    handle_arp_reply_U0_ap_idle;
wire    handle_arp_reply_U0_ap_ready;
wire    handle_arp_reply_U0_dataStreamBuffer2_V_read;
wire   [576:0] handle_arp_reply_U0_dataStreamBuffer3_V_din;
wire    handle_arp_reply_U0_dataStreamBuffer3_V_write;
wire   [128:0] handle_arp_reply_U0_headerFifo_V_din;
wire    handle_arp_reply_U0_headerFifo_V_write;
wire    handle_arp_reply_U0_arpTableIn_V_TREADY;
wire    mac_lshiftWordByOcte_U0_ap_start;
wire    mac_lshiftWordByOcte_U0_ap_done;
wire    mac_lshiftWordByOcte_U0_ap_continue;
wire    mac_lshiftWordByOcte_U0_ap_idle;
wire    mac_lshiftWordByOcte_U0_ap_ready;
wire    mac_lshiftWordByOcte_U0_dataStreamBuffer3_V_read;
wire   [576:0] mac_lshiftWordByOcte_U0_dataStreamBuffer4_V_din;
wire    mac_lshiftWordByOcte_U0_dataStreamBuffer4_V_write;
wire    insert_ethernet_head_U0_ap_start;
wire    insert_ethernet_head_U0_ap_done;
wire    insert_ethernet_head_U0_ap_continue;
wire    insert_ethernet_head_U0_ap_idle;
wire    insert_ethernet_head_U0_ap_ready;
wire    insert_ethernet_head_U0_dataStreamBuffer4_V_read;
wire    insert_ethernet_head_U0_headerFifo_V_read;
wire   [511:0] insert_ethernet_head_U0_m_axis_ip_TDATA;
wire    insert_ethernet_head_U0_m_axis_ip_TVALID;
wire   [63:0] insert_ethernet_head_U0_m_axis_ip_TKEEP;
wire   [0:0] insert_ethernet_head_U0_m_axis_ip_TLAST;
wire    dataStreamBuffer0_V_full_n;
wire   [576:0] dataStreamBuffer0_V_dout;
wire    dataStreamBuffer0_V_empty_n;
wire    dataStreamBuffer1_V_full_n;
wire   [576:0] dataStreamBuffer1_V_dout;
wire    dataStreamBuffer1_V_empty_n;
wire    subSumFifo_V_sum_V_0_full_n;
wire   [16:0] subSumFifo_V_sum_V_0_dout;
wire    subSumFifo_V_sum_V_0_empty_n;
wire    subSumFifo_V_sum_V_1_full_n;
wire   [16:0] subSumFifo_V_sum_V_1_dout;
wire    subSumFifo_V_sum_V_1_empty_n;
wire    subSumFifo_V_sum_V_2_full_n;
wire   [16:0] subSumFifo_V_sum_V_2_dout;
wire    subSumFifo_V_sum_V_2_empty_n;
wire    subSumFifo_V_sum_V_3_full_n;
wire   [16:0] subSumFifo_V_sum_V_3_dout;
wire    subSumFifo_V_sum_V_3_empty_n;
wire    subSumFifo_V_sum_V_4_full_n;
wire   [16:0] subSumFifo_V_sum_V_4_dout;
wire    subSumFifo_V_sum_V_4_empty_n;
wire    subSumFifo_V_sum_V_5_full_n;
wire   [16:0] subSumFifo_V_sum_V_5_dout;
wire    subSumFifo_V_sum_V_5_empty_n;
wire    subSumFifo_V_sum_V_6_full_n;
wire   [16:0] subSumFifo_V_sum_V_6_dout;
wire    subSumFifo_V_sum_V_6_empty_n;
wire    subSumFifo_V_sum_V_7_full_n;
wire   [16:0] subSumFifo_V_sum_V_7_dout;
wire    subSumFifo_V_sum_V_7_empty_n;
wire    subSumFifo_V_sum_V_8_full_n;
wire   [16:0] subSumFifo_V_sum_V_8_dout;
wire    subSumFifo_V_sum_V_8_empty_n;
wire    subSumFifo_V_sum_V_9_full_n;
wire   [16:0] subSumFifo_V_sum_V_9_dout;
wire    subSumFifo_V_sum_V_9_empty_n;
wire    subSumFifo_V_sum_V_10_full_n;
wire   [16:0] subSumFifo_V_sum_V_10_dout;
wire    subSumFifo_V_sum_V_10_empty_n;
wire    subSumFifo_V_sum_V_11_full_n;
wire   [16:0] subSumFifo_V_sum_V_11_dout;
wire    subSumFifo_V_sum_V_11_empty_n;
wire    subSumFifo_V_sum_V_12_full_n;
wire   [16:0] subSumFifo_V_sum_V_12_dout;
wire    subSumFifo_V_sum_V_12_empty_n;
wire    subSumFifo_V_sum_V_13_full_n;
wire   [16:0] subSumFifo_V_sum_V_13_dout;
wire    subSumFifo_V_sum_V_13_empty_n;
wire    subSumFifo_V_sum_V_14_full_n;
wire   [16:0] subSumFifo_V_sum_V_14_dout;
wire    subSumFifo_V_sum_V_14_empty_n;
wire    subSumFifo_V_sum_V_15_full_n;
wire   [16:0] subSumFifo_V_sum_V_15_dout;
wire    subSumFifo_V_sum_V_15_empty_n;
wire    subSumFifo_V_sum_V_16_full_n;
wire   [16:0] subSumFifo_V_sum_V_16_dout;
wire    subSumFifo_V_sum_V_16_empty_n;
wire    subSumFifo_V_sum_V_17_full_n;
wire   [16:0] subSumFifo_V_sum_V_17_dout;
wire    subSumFifo_V_sum_V_17_empty_n;
wire    subSumFifo_V_sum_V_18_full_n;
wire   [16:0] subSumFifo_V_sum_V_18_dout;
wire    subSumFifo_V_sum_V_18_empty_n;
wire    subSumFifo_V_sum_V_19_full_n;
wire   [16:0] subSumFifo_V_sum_V_19_dout;
wire    subSumFifo_V_sum_V_19_empty_n;
wire    subSumFifo_V_sum_V_20_full_n;
wire   [16:0] subSumFifo_V_sum_V_20_dout;
wire    subSumFifo_V_sum_V_20_empty_n;
wire    subSumFifo_V_sum_V_21_full_n;
wire   [16:0] subSumFifo_V_sum_V_21_dout;
wire    subSumFifo_V_sum_V_21_empty_n;
wire    subSumFifo_V_sum_V_22_full_n;
wire   [16:0] subSumFifo_V_sum_V_22_dout;
wire    subSumFifo_V_sum_V_22_empty_n;
wire    subSumFifo_V_sum_V_23_full_n;
wire   [16:0] subSumFifo_V_sum_V_23_dout;
wire    subSumFifo_V_sum_V_23_empty_n;
wire    subSumFifo_V_sum_V_24_full_n;
wire   [16:0] subSumFifo_V_sum_V_24_dout;
wire    subSumFifo_V_sum_V_24_empty_n;
wire    subSumFifo_V_sum_V_25_full_n;
wire   [16:0] subSumFifo_V_sum_V_25_dout;
wire    subSumFifo_V_sum_V_25_empty_n;
wire    subSumFifo_V_sum_V_26_full_n;
wire   [16:0] subSumFifo_V_sum_V_26_dout;
wire    subSumFifo_V_sum_V_26_empty_n;
wire    subSumFifo_V_sum_V_27_full_n;
wire   [16:0] subSumFifo_V_sum_V_27_dout;
wire    subSumFifo_V_sum_V_27_empty_n;
wire    subSumFifo_V_sum_V_28_full_n;
wire   [16:0] subSumFifo_V_sum_V_28_dout;
wire    subSumFifo_V_sum_V_28_empty_n;
wire    subSumFifo_V_sum_V_29_full_n;
wire   [16:0] subSumFifo_V_sum_V_29_dout;
wire    subSumFifo_V_sum_V_29_empty_n;
wire    subSumFifo_V_sum_V_30_full_n;
wire   [16:0] subSumFifo_V_sum_V_30_dout;
wire    subSumFifo_V_sum_V_30_empty_n;
wire    subSumFifo_V_sum_V_31_full_n;
wire   [16:0] subSumFifo_V_sum_V_31_dout;
wire    subSumFifo_V_sum_V_31_empty_n;
wire    checksumFifo_V_V_full_n;
wire   [15:0] checksumFifo_V_V_dout;
wire    checksumFifo_V_V_empty_n;
wire    dataStreamBuffer2_V_full_n;
wire   [576:0] dataStreamBuffer2_V_dout;
wire    dataStreamBuffer2_V_empty_n;
wire    headerFifo_V_full_n;
wire   [128:0] headerFifo_V_dout;
wire    headerFifo_V_empty_n;
wire    dataStreamBuffer3_V_full_n;
wire   [576:0] dataStreamBuffer3_V_dout;
wire    dataStreamBuffer3_V_empty_n;
wire    dataStreamBuffer4_V_full_n;
wire   [576:0] dataStreamBuffer4_V_dout;
wire    dataStreamBuffer4_V_empty_n;

extract_ip_address extract_ip_address_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(extract_ip_address_U0_ap_start),
    .ap_done(extract_ip_address_U0_ap_done),
    .ap_continue(extract_ip_address_U0_ap_continue),
    .ap_idle(extract_ip_address_U0_ap_idle),
    .ap_ready(extract_ip_address_U0_ap_ready),
    .s_axis_ip_TVALID(s_axis_ip_TVALID),
    .dataStreamBuffer0_V_din(extract_ip_address_U0_dataStreamBuffer0_V_din),
    .dataStreamBuffer0_V_full_n(dataStreamBuffer0_V_full_n),
    .dataStreamBuffer0_V_write(extract_ip_address_U0_dataStreamBuffer0_V_write),
    .arpTableOut_V_V_TREADY(m_axis_arp_lookup_request_V_V_TREADY),
    .s_axis_ip_TDATA(s_axis_ip_TDATA),
    .s_axis_ip_TREADY(extract_ip_address_U0_s_axis_ip_TREADY),
    .s_axis_ip_TKEEP(s_axis_ip_TKEEP),
    .s_axis_ip_TLAST(s_axis_ip_TLAST),
    .arpTableOut_V_V_TDATA(extract_ip_address_U0_arpTableOut_V_V_TDATA),
    .arpTableOut_V_V_TVALID(extract_ip_address_U0_arpTableOut_V_V_TVALID),
    .regSubNetMask_V(regSubNetMask_V),
    .regDefaultGateway_V(regDefaultGateway_V)
);

mac_compute_ipv4_che mac_compute_ipv4_che_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(mac_compute_ipv4_che_U0_ap_start),
    .ap_done(mac_compute_ipv4_che_U0_ap_done),
    .ap_continue(mac_compute_ipv4_che_U0_ap_continue),
    .ap_idle(mac_compute_ipv4_che_U0_ap_idle),
    .ap_ready(mac_compute_ipv4_che_U0_ap_ready),
    .dataStreamBuffer0_V_dout(dataStreamBuffer0_V_dout),
    .dataStreamBuffer0_V_empty_n(dataStreamBuffer0_V_empty_n),
    .dataStreamBuffer0_V_read(mac_compute_ipv4_che_U0_dataStreamBuffer0_V_read),
    .dataStreamBuffer1_V_din(mac_compute_ipv4_che_U0_dataStreamBuffer1_V_din),
    .dataStreamBuffer1_V_full_n(dataStreamBuffer1_V_full_n),
    .dataStreamBuffer1_V_write(mac_compute_ipv4_che_U0_dataStreamBuffer1_V_write),
    .subSumFifo_V_sum_V_0_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_0_din),
    .subSumFifo_V_sum_V_0_full_n(subSumFifo_V_sum_V_0_full_n),
    .subSumFifo_V_sum_V_0_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_0_write),
    .subSumFifo_V_sum_V_1_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_1_din),
    .subSumFifo_V_sum_V_1_full_n(subSumFifo_V_sum_V_1_full_n),
    .subSumFifo_V_sum_V_1_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_1_write),
    .subSumFifo_V_sum_V_2_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_2_din),
    .subSumFifo_V_sum_V_2_full_n(subSumFifo_V_sum_V_2_full_n),
    .subSumFifo_V_sum_V_2_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_2_write),
    .subSumFifo_V_sum_V_3_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_3_din),
    .subSumFifo_V_sum_V_3_full_n(subSumFifo_V_sum_V_3_full_n),
    .subSumFifo_V_sum_V_3_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_3_write),
    .subSumFifo_V_sum_V_4_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_4_din),
    .subSumFifo_V_sum_V_4_full_n(subSumFifo_V_sum_V_4_full_n),
    .subSumFifo_V_sum_V_4_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_4_write),
    .subSumFifo_V_sum_V_5_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_5_din),
    .subSumFifo_V_sum_V_5_full_n(subSumFifo_V_sum_V_5_full_n),
    .subSumFifo_V_sum_V_5_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_5_write),
    .subSumFifo_V_sum_V_6_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_6_din),
    .subSumFifo_V_sum_V_6_full_n(subSumFifo_V_sum_V_6_full_n),
    .subSumFifo_V_sum_V_6_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_6_write),
    .subSumFifo_V_sum_V_7_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_7_din),
    .subSumFifo_V_sum_V_7_full_n(subSumFifo_V_sum_V_7_full_n),
    .subSumFifo_V_sum_V_7_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_7_write),
    .subSumFifo_V_sum_V_8_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_8_din),
    .subSumFifo_V_sum_V_8_full_n(subSumFifo_V_sum_V_8_full_n),
    .subSumFifo_V_sum_V_8_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_8_write),
    .subSumFifo_V_sum_V_9_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_9_din),
    .subSumFifo_V_sum_V_9_full_n(subSumFifo_V_sum_V_9_full_n),
    .subSumFifo_V_sum_V_9_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_9_write),
    .subSumFifo_V_sum_V_10_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_10_din),
    .subSumFifo_V_sum_V_10_full_n(subSumFifo_V_sum_V_10_full_n),
    .subSumFifo_V_sum_V_10_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_10_write),
    .subSumFifo_V_sum_V_11_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_11_din),
    .subSumFifo_V_sum_V_11_full_n(subSumFifo_V_sum_V_11_full_n),
    .subSumFifo_V_sum_V_11_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_11_write),
    .subSumFifo_V_sum_V_12_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_12_din),
    .subSumFifo_V_sum_V_12_full_n(subSumFifo_V_sum_V_12_full_n),
    .subSumFifo_V_sum_V_12_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_12_write),
    .subSumFifo_V_sum_V_13_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_13_din),
    .subSumFifo_V_sum_V_13_full_n(subSumFifo_V_sum_V_13_full_n),
    .subSumFifo_V_sum_V_13_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_13_write),
    .subSumFifo_V_sum_V_14_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_14_din),
    .subSumFifo_V_sum_V_14_full_n(subSumFifo_V_sum_V_14_full_n),
    .subSumFifo_V_sum_V_14_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_14_write),
    .subSumFifo_V_sum_V_15_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_15_din),
    .subSumFifo_V_sum_V_15_full_n(subSumFifo_V_sum_V_15_full_n),
    .subSumFifo_V_sum_V_15_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_15_write),
    .subSumFifo_V_sum_V_16_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_16_din),
    .subSumFifo_V_sum_V_16_full_n(subSumFifo_V_sum_V_16_full_n),
    .subSumFifo_V_sum_V_16_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_16_write),
    .subSumFifo_V_sum_V_17_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_17_din),
    .subSumFifo_V_sum_V_17_full_n(subSumFifo_V_sum_V_17_full_n),
    .subSumFifo_V_sum_V_17_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_17_write),
    .subSumFifo_V_sum_V_18_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_18_din),
    .subSumFifo_V_sum_V_18_full_n(subSumFifo_V_sum_V_18_full_n),
    .subSumFifo_V_sum_V_18_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_18_write),
    .subSumFifo_V_sum_V_19_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_19_din),
    .subSumFifo_V_sum_V_19_full_n(subSumFifo_V_sum_V_19_full_n),
    .subSumFifo_V_sum_V_19_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_19_write),
    .subSumFifo_V_sum_V_20_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_20_din),
    .subSumFifo_V_sum_V_20_full_n(subSumFifo_V_sum_V_20_full_n),
    .subSumFifo_V_sum_V_20_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_20_write),
    .subSumFifo_V_sum_V_21_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_21_din),
    .subSumFifo_V_sum_V_21_full_n(subSumFifo_V_sum_V_21_full_n),
    .subSumFifo_V_sum_V_21_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_21_write),
    .subSumFifo_V_sum_V_22_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_22_din),
    .subSumFifo_V_sum_V_22_full_n(subSumFifo_V_sum_V_22_full_n),
    .subSumFifo_V_sum_V_22_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_22_write),
    .subSumFifo_V_sum_V_23_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_23_din),
    .subSumFifo_V_sum_V_23_full_n(subSumFifo_V_sum_V_23_full_n),
    .subSumFifo_V_sum_V_23_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_23_write),
    .subSumFifo_V_sum_V_24_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_24_din),
    .subSumFifo_V_sum_V_24_full_n(subSumFifo_V_sum_V_24_full_n),
    .subSumFifo_V_sum_V_24_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_24_write),
    .subSumFifo_V_sum_V_25_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_25_din),
    .subSumFifo_V_sum_V_25_full_n(subSumFifo_V_sum_V_25_full_n),
    .subSumFifo_V_sum_V_25_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_25_write),
    .subSumFifo_V_sum_V_26_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_26_din),
    .subSumFifo_V_sum_V_26_full_n(subSumFifo_V_sum_V_26_full_n),
    .subSumFifo_V_sum_V_26_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_26_write),
    .subSumFifo_V_sum_V_27_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_27_din),
    .subSumFifo_V_sum_V_27_full_n(subSumFifo_V_sum_V_27_full_n),
    .subSumFifo_V_sum_V_27_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_27_write),
    .subSumFifo_V_sum_V_28_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_28_din),
    .subSumFifo_V_sum_V_28_full_n(subSumFifo_V_sum_V_28_full_n),
    .subSumFifo_V_sum_V_28_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_28_write),
    .subSumFifo_V_sum_V_29_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_29_din),
    .subSumFifo_V_sum_V_29_full_n(subSumFifo_V_sum_V_29_full_n),
    .subSumFifo_V_sum_V_29_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_29_write),
    .subSumFifo_V_sum_V_30_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_30_din),
    .subSumFifo_V_sum_V_30_full_n(subSumFifo_V_sum_V_30_full_n),
    .subSumFifo_V_sum_V_30_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_30_write),
    .subSumFifo_V_sum_V_31_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_31_din),
    .subSumFifo_V_sum_V_31_full_n(subSumFifo_V_sum_V_31_full_n),
    .subSumFifo_V_sum_V_31_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_31_write)
);

mac_finalize_ipv4_ch mac_finalize_ipv4_ch_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(mac_finalize_ipv4_ch_U0_ap_start),
    .ap_done(mac_finalize_ipv4_ch_U0_ap_done),
    .ap_continue(mac_finalize_ipv4_ch_U0_ap_continue),
    .ap_idle(mac_finalize_ipv4_ch_U0_ap_idle),
    .ap_ready(mac_finalize_ipv4_ch_U0_ap_ready),
    .subSumFifo_V_sum_V_0_dout(subSumFifo_V_sum_V_0_dout),
    .subSumFifo_V_sum_V_0_empty_n(subSumFifo_V_sum_V_0_empty_n),
    .subSumFifo_V_sum_V_0_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_0_read),
    .subSumFifo_V_sum_V_1_dout(subSumFifo_V_sum_V_1_dout),
    .subSumFifo_V_sum_V_1_empty_n(subSumFifo_V_sum_V_1_empty_n),
    .subSumFifo_V_sum_V_1_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_1_read),
    .subSumFifo_V_sum_V_2_dout(subSumFifo_V_sum_V_2_dout),
    .subSumFifo_V_sum_V_2_empty_n(subSumFifo_V_sum_V_2_empty_n),
    .subSumFifo_V_sum_V_2_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_2_read),
    .subSumFifo_V_sum_V_3_dout(subSumFifo_V_sum_V_3_dout),
    .subSumFifo_V_sum_V_3_empty_n(subSumFifo_V_sum_V_3_empty_n),
    .subSumFifo_V_sum_V_3_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_3_read),
    .subSumFifo_V_sum_V_4_dout(subSumFifo_V_sum_V_4_dout),
    .subSumFifo_V_sum_V_4_empty_n(subSumFifo_V_sum_V_4_empty_n),
    .subSumFifo_V_sum_V_4_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_4_read),
    .subSumFifo_V_sum_V_5_dout(subSumFifo_V_sum_V_5_dout),
    .subSumFifo_V_sum_V_5_empty_n(subSumFifo_V_sum_V_5_empty_n),
    .subSumFifo_V_sum_V_5_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_5_read),
    .subSumFifo_V_sum_V_6_dout(subSumFifo_V_sum_V_6_dout),
    .subSumFifo_V_sum_V_6_empty_n(subSumFifo_V_sum_V_6_empty_n),
    .subSumFifo_V_sum_V_6_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_6_read),
    .subSumFifo_V_sum_V_7_dout(subSumFifo_V_sum_V_7_dout),
    .subSumFifo_V_sum_V_7_empty_n(subSumFifo_V_sum_V_7_empty_n),
    .subSumFifo_V_sum_V_7_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_7_read),
    .subSumFifo_V_sum_V_8_dout(subSumFifo_V_sum_V_8_dout),
    .subSumFifo_V_sum_V_8_empty_n(subSumFifo_V_sum_V_8_empty_n),
    .subSumFifo_V_sum_V_8_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_8_read),
    .subSumFifo_V_sum_V_9_dout(subSumFifo_V_sum_V_9_dout),
    .subSumFifo_V_sum_V_9_empty_n(subSumFifo_V_sum_V_9_empty_n),
    .subSumFifo_V_sum_V_9_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_9_read),
    .subSumFifo_V_sum_V_10_dout(subSumFifo_V_sum_V_10_dout),
    .subSumFifo_V_sum_V_10_empty_n(subSumFifo_V_sum_V_10_empty_n),
    .subSumFifo_V_sum_V_10_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_10_read),
    .subSumFifo_V_sum_V_11_dout(subSumFifo_V_sum_V_11_dout),
    .subSumFifo_V_sum_V_11_empty_n(subSumFifo_V_sum_V_11_empty_n),
    .subSumFifo_V_sum_V_11_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_11_read),
    .subSumFifo_V_sum_V_12_dout(subSumFifo_V_sum_V_12_dout),
    .subSumFifo_V_sum_V_12_empty_n(subSumFifo_V_sum_V_12_empty_n),
    .subSumFifo_V_sum_V_12_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_12_read),
    .subSumFifo_V_sum_V_13_dout(subSumFifo_V_sum_V_13_dout),
    .subSumFifo_V_sum_V_13_empty_n(subSumFifo_V_sum_V_13_empty_n),
    .subSumFifo_V_sum_V_13_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_13_read),
    .subSumFifo_V_sum_V_14_dout(subSumFifo_V_sum_V_14_dout),
    .subSumFifo_V_sum_V_14_empty_n(subSumFifo_V_sum_V_14_empty_n),
    .subSumFifo_V_sum_V_14_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_14_read),
    .subSumFifo_V_sum_V_15_dout(subSumFifo_V_sum_V_15_dout),
    .subSumFifo_V_sum_V_15_empty_n(subSumFifo_V_sum_V_15_empty_n),
    .subSumFifo_V_sum_V_15_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_15_read),
    .subSumFifo_V_sum_V_16_dout(subSumFifo_V_sum_V_16_dout),
    .subSumFifo_V_sum_V_16_empty_n(subSumFifo_V_sum_V_16_empty_n),
    .subSumFifo_V_sum_V_16_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_16_read),
    .subSumFifo_V_sum_V_17_dout(subSumFifo_V_sum_V_17_dout),
    .subSumFifo_V_sum_V_17_empty_n(subSumFifo_V_sum_V_17_empty_n),
    .subSumFifo_V_sum_V_17_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_17_read),
    .subSumFifo_V_sum_V_18_dout(subSumFifo_V_sum_V_18_dout),
    .subSumFifo_V_sum_V_18_empty_n(subSumFifo_V_sum_V_18_empty_n),
    .subSumFifo_V_sum_V_18_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_18_read),
    .subSumFifo_V_sum_V_19_dout(subSumFifo_V_sum_V_19_dout),
    .subSumFifo_V_sum_V_19_empty_n(subSumFifo_V_sum_V_19_empty_n),
    .subSumFifo_V_sum_V_19_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_19_read),
    .subSumFifo_V_sum_V_20_dout(subSumFifo_V_sum_V_20_dout),
    .subSumFifo_V_sum_V_20_empty_n(subSumFifo_V_sum_V_20_empty_n),
    .subSumFifo_V_sum_V_20_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_20_read),
    .subSumFifo_V_sum_V_21_dout(subSumFifo_V_sum_V_21_dout),
    .subSumFifo_V_sum_V_21_empty_n(subSumFifo_V_sum_V_21_empty_n),
    .subSumFifo_V_sum_V_21_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_21_read),
    .subSumFifo_V_sum_V_22_dout(subSumFifo_V_sum_V_22_dout),
    .subSumFifo_V_sum_V_22_empty_n(subSumFifo_V_sum_V_22_empty_n),
    .subSumFifo_V_sum_V_22_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_22_read),
    .subSumFifo_V_sum_V_23_dout(subSumFifo_V_sum_V_23_dout),
    .subSumFifo_V_sum_V_23_empty_n(subSumFifo_V_sum_V_23_empty_n),
    .subSumFifo_V_sum_V_23_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_23_read),
    .subSumFifo_V_sum_V_24_dout(subSumFifo_V_sum_V_24_dout),
    .subSumFifo_V_sum_V_24_empty_n(subSumFifo_V_sum_V_24_empty_n),
    .subSumFifo_V_sum_V_24_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_24_read),
    .subSumFifo_V_sum_V_25_dout(subSumFifo_V_sum_V_25_dout),
    .subSumFifo_V_sum_V_25_empty_n(subSumFifo_V_sum_V_25_empty_n),
    .subSumFifo_V_sum_V_25_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_25_read),
    .subSumFifo_V_sum_V_26_dout(subSumFifo_V_sum_V_26_dout),
    .subSumFifo_V_sum_V_26_empty_n(subSumFifo_V_sum_V_26_empty_n),
    .subSumFifo_V_sum_V_26_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_26_read),
    .subSumFifo_V_sum_V_27_dout(subSumFifo_V_sum_V_27_dout),
    .subSumFifo_V_sum_V_27_empty_n(subSumFifo_V_sum_V_27_empty_n),
    .subSumFifo_V_sum_V_27_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_27_read),
    .subSumFifo_V_sum_V_28_dout(subSumFifo_V_sum_V_28_dout),
    .subSumFifo_V_sum_V_28_empty_n(subSumFifo_V_sum_V_28_empty_n),
    .subSumFifo_V_sum_V_28_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_28_read),
    .subSumFifo_V_sum_V_29_dout(subSumFifo_V_sum_V_29_dout),
    .subSumFifo_V_sum_V_29_empty_n(subSumFifo_V_sum_V_29_empty_n),
    .subSumFifo_V_sum_V_29_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_29_read),
    .subSumFifo_V_sum_V_30_dout(subSumFifo_V_sum_V_30_dout),
    .subSumFifo_V_sum_V_30_empty_n(subSumFifo_V_sum_V_30_empty_n),
    .subSumFifo_V_sum_V_30_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_30_read),
    .subSumFifo_V_sum_V_31_dout(subSumFifo_V_sum_V_31_dout),
    .subSumFifo_V_sum_V_31_empty_n(subSumFifo_V_sum_V_31_empty_n),
    .subSumFifo_V_sum_V_31_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_31_read),
    .checksumFifo_V_V_din(mac_finalize_ipv4_ch_U0_checksumFifo_V_V_din),
    .checksumFifo_V_V_full_n(checksumFifo_V_V_full_n),
    .checksumFifo_V_V_write(mac_finalize_ipv4_ch_U0_checksumFifo_V_V_write)
);

insert_ip_checksum insert_ip_checksum_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(insert_ip_checksum_U0_ap_start),
    .ap_done(insert_ip_checksum_U0_ap_done),
    .ap_continue(insert_ip_checksum_U0_ap_continue),
    .ap_idle(insert_ip_checksum_U0_ap_idle),
    .ap_ready(insert_ip_checksum_U0_ap_ready),
    .dataStreamBuffer1_V_dout(dataStreamBuffer1_V_dout),
    .dataStreamBuffer1_V_empty_n(dataStreamBuffer1_V_empty_n),
    .dataStreamBuffer1_V_read(insert_ip_checksum_U0_dataStreamBuffer1_V_read),
    .checksumFifo_V_V_dout(checksumFifo_V_V_dout),
    .checksumFifo_V_V_empty_n(checksumFifo_V_V_empty_n),
    .checksumFifo_V_V_read(insert_ip_checksum_U0_checksumFifo_V_V_read),
    .dataStreamBuffer2_V_din(insert_ip_checksum_U0_dataStreamBuffer2_V_din),
    .dataStreamBuffer2_V_full_n(dataStreamBuffer2_V_full_n),
    .dataStreamBuffer2_V_write(insert_ip_checksum_U0_dataStreamBuffer2_V_write)
);

handle_arp_reply handle_arp_reply_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(handle_arp_reply_U0_ap_start),
    .ap_done(handle_arp_reply_U0_ap_done),
    .ap_continue(handle_arp_reply_U0_ap_continue),
    .ap_idle(handle_arp_reply_U0_ap_idle),
    .ap_ready(handle_arp_reply_U0_ap_ready),
    .dataStreamBuffer2_V_dout(dataStreamBuffer2_V_dout),
    .dataStreamBuffer2_V_empty_n(dataStreamBuffer2_V_empty_n),
    .dataStreamBuffer2_V_read(handle_arp_reply_U0_dataStreamBuffer2_V_read),
    .arpTableIn_V_TVALID(s_axis_arp_lookup_reply_V_TVALID),
    .dataStreamBuffer3_V_din(handle_arp_reply_U0_dataStreamBuffer3_V_din),
    .dataStreamBuffer3_V_full_n(dataStreamBuffer3_V_full_n),
    .dataStreamBuffer3_V_write(handle_arp_reply_U0_dataStreamBuffer3_V_write),
    .headerFifo_V_din(handle_arp_reply_U0_headerFifo_V_din),
    .headerFifo_V_full_n(headerFifo_V_full_n),
    .headerFifo_V_write(handle_arp_reply_U0_headerFifo_V_write),
    .arpTableIn_V_TDATA(s_axis_arp_lookup_reply_V_TDATA),
    .arpTableIn_V_TREADY(handle_arp_reply_U0_arpTableIn_V_TREADY),
    .myMacAddress_V(myMacAddress_V)
);

mac_lshiftWordByOcte mac_lshiftWordByOcte_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(mac_lshiftWordByOcte_U0_ap_start),
    .ap_done(mac_lshiftWordByOcte_U0_ap_done),
    .ap_continue(mac_lshiftWordByOcte_U0_ap_continue),
    .ap_idle(mac_lshiftWordByOcte_U0_ap_idle),
    .ap_ready(mac_lshiftWordByOcte_U0_ap_ready),
    .dataStreamBuffer3_V_dout(dataStreamBuffer3_V_dout),
    .dataStreamBuffer3_V_empty_n(dataStreamBuffer3_V_empty_n),
    .dataStreamBuffer3_V_read(mac_lshiftWordByOcte_U0_dataStreamBuffer3_V_read),
    .dataStreamBuffer4_V_din(mac_lshiftWordByOcte_U0_dataStreamBuffer4_V_din),
    .dataStreamBuffer4_V_full_n(dataStreamBuffer4_V_full_n),
    .dataStreamBuffer4_V_write(mac_lshiftWordByOcte_U0_dataStreamBuffer4_V_write)
);

insert_ethernet_head insert_ethernet_head_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(insert_ethernet_head_U0_ap_start),
    .ap_done(insert_ethernet_head_U0_ap_done),
    .ap_continue(insert_ethernet_head_U0_ap_continue),
    .ap_idle(insert_ethernet_head_U0_ap_idle),
    .ap_ready(insert_ethernet_head_U0_ap_ready),
    .dataStreamBuffer4_V_dout(dataStreamBuffer4_V_dout),
    .dataStreamBuffer4_V_empty_n(dataStreamBuffer4_V_empty_n),
    .dataStreamBuffer4_V_read(insert_ethernet_head_U0_dataStreamBuffer4_V_read),
    .headerFifo_V_dout(headerFifo_V_dout),
    .headerFifo_V_empty_n(headerFifo_V_empty_n),
    .headerFifo_V_read(insert_ethernet_head_U0_headerFifo_V_read),
    .m_axis_ip_TREADY(m_axis_ip_TREADY),
    .m_axis_ip_TDATA(insert_ethernet_head_U0_m_axis_ip_TDATA),
    .m_axis_ip_TVALID(insert_ethernet_head_U0_m_axis_ip_TVALID),
    .m_axis_ip_TKEEP(insert_ethernet_head_U0_m_axis_ip_TKEEP),
    .m_axis_ip_TLAST(insert_ethernet_head_U0_m_axis_ip_TLAST)
);

fifo_w577_d2_A dataStreamBuffer0_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(extract_ip_address_U0_dataStreamBuffer0_V_din),
    .if_full_n(dataStreamBuffer0_V_full_n),
    .if_write(extract_ip_address_U0_dataStreamBuffer0_V_write),
    .if_dout(dataStreamBuffer0_V_dout),
    .if_empty_n(dataStreamBuffer0_V_empty_n),
    .if_read(mac_compute_ipv4_che_U0_dataStreamBuffer0_V_read)
);

fifo_w577_d32_A dataStreamBuffer1_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_dataStreamBuffer1_V_din),
    .if_full_n(dataStreamBuffer1_V_full_n),
    .if_write(mac_compute_ipv4_che_U0_dataStreamBuffer1_V_write),
    .if_dout(dataStreamBuffer1_V_dout),
    .if_empty_n(dataStreamBuffer1_V_empty_n),
    .if_read(insert_ip_checksum_U0_dataStreamBuffer1_V_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_0_din),
    .if_full_n(subSumFifo_V_sum_V_0_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_0_write),
    .if_dout(subSumFifo_V_sum_V_0_dout),
    .if_empty_n(subSumFifo_V_sum_V_0_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_0_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_1_din),
    .if_full_n(subSumFifo_V_sum_V_1_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_1_write),
    .if_dout(subSumFifo_V_sum_V_1_dout),
    .if_empty_n(subSumFifo_V_sum_V_1_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_1_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_2_din),
    .if_full_n(subSumFifo_V_sum_V_2_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_2_write),
    .if_dout(subSumFifo_V_sum_V_2_dout),
    .if_empty_n(subSumFifo_V_sum_V_2_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_2_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_3_din),
    .if_full_n(subSumFifo_V_sum_V_3_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_3_write),
    .if_dout(subSumFifo_V_sum_V_3_dout),
    .if_empty_n(subSumFifo_V_sum_V_3_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_3_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_4_din),
    .if_full_n(subSumFifo_V_sum_V_4_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_4_write),
    .if_dout(subSumFifo_V_sum_V_4_dout),
    .if_empty_n(subSumFifo_V_sum_V_4_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_4_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_5_din),
    .if_full_n(subSumFifo_V_sum_V_5_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_5_write),
    .if_dout(subSumFifo_V_sum_V_5_dout),
    .if_empty_n(subSumFifo_V_sum_V_5_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_5_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_6_din),
    .if_full_n(subSumFifo_V_sum_V_6_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_6_write),
    .if_dout(subSumFifo_V_sum_V_6_dout),
    .if_empty_n(subSumFifo_V_sum_V_6_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_6_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_7_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_7_din),
    .if_full_n(subSumFifo_V_sum_V_7_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_7_write),
    .if_dout(subSumFifo_V_sum_V_7_dout),
    .if_empty_n(subSumFifo_V_sum_V_7_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_7_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_8_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_8_din),
    .if_full_n(subSumFifo_V_sum_V_8_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_8_write),
    .if_dout(subSumFifo_V_sum_V_8_dout),
    .if_empty_n(subSumFifo_V_sum_V_8_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_8_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_9_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_9_din),
    .if_full_n(subSumFifo_V_sum_V_9_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_9_write),
    .if_dout(subSumFifo_V_sum_V_9_dout),
    .if_empty_n(subSumFifo_V_sum_V_9_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_9_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_10_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_10_din),
    .if_full_n(subSumFifo_V_sum_V_10_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_10_write),
    .if_dout(subSumFifo_V_sum_V_10_dout),
    .if_empty_n(subSumFifo_V_sum_V_10_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_10_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_11_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_11_din),
    .if_full_n(subSumFifo_V_sum_V_11_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_11_write),
    .if_dout(subSumFifo_V_sum_V_11_dout),
    .if_empty_n(subSumFifo_V_sum_V_11_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_11_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_12_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_12_din),
    .if_full_n(subSumFifo_V_sum_V_12_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_12_write),
    .if_dout(subSumFifo_V_sum_V_12_dout),
    .if_empty_n(subSumFifo_V_sum_V_12_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_12_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_13_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_13_din),
    .if_full_n(subSumFifo_V_sum_V_13_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_13_write),
    .if_dout(subSumFifo_V_sum_V_13_dout),
    .if_empty_n(subSumFifo_V_sum_V_13_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_13_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_14_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_14_din),
    .if_full_n(subSumFifo_V_sum_V_14_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_14_write),
    .if_dout(subSumFifo_V_sum_V_14_dout),
    .if_empty_n(subSumFifo_V_sum_V_14_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_14_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_15_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_15_din),
    .if_full_n(subSumFifo_V_sum_V_15_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_15_write),
    .if_dout(subSumFifo_V_sum_V_15_dout),
    .if_empty_n(subSumFifo_V_sum_V_15_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_15_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_16_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_16_din),
    .if_full_n(subSumFifo_V_sum_V_16_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_16_write),
    .if_dout(subSumFifo_V_sum_V_16_dout),
    .if_empty_n(subSumFifo_V_sum_V_16_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_16_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_17_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_17_din),
    .if_full_n(subSumFifo_V_sum_V_17_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_17_write),
    .if_dout(subSumFifo_V_sum_V_17_dout),
    .if_empty_n(subSumFifo_V_sum_V_17_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_17_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_18_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_18_din),
    .if_full_n(subSumFifo_V_sum_V_18_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_18_write),
    .if_dout(subSumFifo_V_sum_V_18_dout),
    .if_empty_n(subSumFifo_V_sum_V_18_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_18_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_19_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_19_din),
    .if_full_n(subSumFifo_V_sum_V_19_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_19_write),
    .if_dout(subSumFifo_V_sum_V_19_dout),
    .if_empty_n(subSumFifo_V_sum_V_19_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_19_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_20_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_20_din),
    .if_full_n(subSumFifo_V_sum_V_20_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_20_write),
    .if_dout(subSumFifo_V_sum_V_20_dout),
    .if_empty_n(subSumFifo_V_sum_V_20_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_20_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_21_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_21_din),
    .if_full_n(subSumFifo_V_sum_V_21_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_21_write),
    .if_dout(subSumFifo_V_sum_V_21_dout),
    .if_empty_n(subSumFifo_V_sum_V_21_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_21_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_22_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_22_din),
    .if_full_n(subSumFifo_V_sum_V_22_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_22_write),
    .if_dout(subSumFifo_V_sum_V_22_dout),
    .if_empty_n(subSumFifo_V_sum_V_22_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_22_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_23_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_23_din),
    .if_full_n(subSumFifo_V_sum_V_23_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_23_write),
    .if_dout(subSumFifo_V_sum_V_23_dout),
    .if_empty_n(subSumFifo_V_sum_V_23_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_23_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_24_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_24_din),
    .if_full_n(subSumFifo_V_sum_V_24_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_24_write),
    .if_dout(subSumFifo_V_sum_V_24_dout),
    .if_empty_n(subSumFifo_V_sum_V_24_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_24_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_25_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_25_din),
    .if_full_n(subSumFifo_V_sum_V_25_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_25_write),
    .if_dout(subSumFifo_V_sum_V_25_dout),
    .if_empty_n(subSumFifo_V_sum_V_25_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_25_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_26_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_26_din),
    .if_full_n(subSumFifo_V_sum_V_26_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_26_write),
    .if_dout(subSumFifo_V_sum_V_26_dout),
    .if_empty_n(subSumFifo_V_sum_V_26_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_26_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_27_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_27_din),
    .if_full_n(subSumFifo_V_sum_V_27_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_27_write),
    .if_dout(subSumFifo_V_sum_V_27_dout),
    .if_empty_n(subSumFifo_V_sum_V_27_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_27_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_28_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_28_din),
    .if_full_n(subSumFifo_V_sum_V_28_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_28_write),
    .if_dout(subSumFifo_V_sum_V_28_dout),
    .if_empty_n(subSumFifo_V_sum_V_28_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_28_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_29_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_29_din),
    .if_full_n(subSumFifo_V_sum_V_29_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_29_write),
    .if_dout(subSumFifo_V_sum_V_29_dout),
    .if_empty_n(subSumFifo_V_sum_V_29_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_29_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_30_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_30_din),
    .if_full_n(subSumFifo_V_sum_V_30_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_30_write),
    .if_dout(subSumFifo_V_sum_V_30_dout),
    .if_empty_n(subSumFifo_V_sum_V_30_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_30_read)
);

fifo_w17_d2_A subSumFifo_V_sum_V_31_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_31_din),
    .if_full_n(subSumFifo_V_sum_V_31_full_n),
    .if_write(mac_compute_ipv4_che_U0_subSumFifo_V_sum_V_31_write),
    .if_dout(subSumFifo_V_sum_V_31_dout),
    .if_empty_n(subSumFifo_V_sum_V_31_empty_n),
    .if_read(mac_finalize_ipv4_ch_U0_subSumFifo_V_sum_V_31_read)
);

fifo_w16_d16_A checksumFifo_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_finalize_ipv4_ch_U0_checksumFifo_V_V_din),
    .if_full_n(checksumFifo_V_V_full_n),
    .if_write(mac_finalize_ipv4_ch_U0_checksumFifo_V_V_write),
    .if_dout(checksumFifo_V_V_dout),
    .if_empty_n(checksumFifo_V_V_empty_n),
    .if_read(insert_ip_checksum_U0_checksumFifo_V_V_read)
);

fifo_w577_d2_A dataStreamBuffer2_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(insert_ip_checksum_U0_dataStreamBuffer2_V_din),
    .if_full_n(dataStreamBuffer2_V_full_n),
    .if_write(insert_ip_checksum_U0_dataStreamBuffer2_V_write),
    .if_dout(dataStreamBuffer2_V_dout),
    .if_empty_n(dataStreamBuffer2_V_empty_n),
    .if_read(handle_arp_reply_U0_dataStreamBuffer2_V_read)
);

fifo_w129_d2_A headerFifo_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(handle_arp_reply_U0_headerFifo_V_din),
    .if_full_n(headerFifo_V_full_n),
    .if_write(handle_arp_reply_U0_headerFifo_V_write),
    .if_dout(headerFifo_V_dout),
    .if_empty_n(headerFifo_V_empty_n),
    .if_read(insert_ethernet_head_U0_headerFifo_V_read)
);

fifo_w577_d2_A dataStreamBuffer3_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(handle_arp_reply_U0_dataStreamBuffer3_V_din),
    .if_full_n(dataStreamBuffer3_V_full_n),
    .if_write(handle_arp_reply_U0_dataStreamBuffer3_V_write),
    .if_dout(dataStreamBuffer3_V_dout),
    .if_empty_n(dataStreamBuffer3_V_empty_n),
    .if_read(mac_lshiftWordByOcte_U0_dataStreamBuffer3_V_read)
);

fifo_w577_d2_A dataStreamBuffer4_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_lshiftWordByOcte_U0_dataStreamBuffer4_V_din),
    .if_full_n(dataStreamBuffer4_V_full_n),
    .if_write(mac_lshiftWordByOcte_U0_dataStreamBuffer4_V_write),
    .if_dout(dataStreamBuffer4_V_dout),
    .if_empty_n(dataStreamBuffer4_V_empty_n),
    .if_read(insert_ethernet_head_U0_dataStreamBuffer4_V_read)
);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b0;

assign extract_ip_address_U0_ap_continue = 1'b1;

assign extract_ip_address_U0_ap_start = 1'b1;

assign handle_arp_reply_U0_ap_continue = 1'b1;

assign handle_arp_reply_U0_ap_start = 1'b1;

assign insert_ethernet_head_U0_ap_continue = 1'b1;

assign insert_ethernet_head_U0_ap_start = 1'b1;

assign insert_ip_checksum_U0_ap_continue = 1'b1;

assign insert_ip_checksum_U0_ap_start = 1'b1;

assign m_axis_arp_lookup_request_V_V_TDATA = extract_ip_address_U0_arpTableOut_V_V_TDATA;

assign m_axis_arp_lookup_request_V_V_TVALID = extract_ip_address_U0_arpTableOut_V_V_TVALID;

assign m_axis_ip_TDATA = insert_ethernet_head_U0_m_axis_ip_TDATA;

assign m_axis_ip_TKEEP = insert_ethernet_head_U0_m_axis_ip_TKEEP;

assign m_axis_ip_TLAST = insert_ethernet_head_U0_m_axis_ip_TLAST;

assign m_axis_ip_TVALID = insert_ethernet_head_U0_m_axis_ip_TVALID;

assign mac_compute_ipv4_che_U0_ap_continue = 1'b1;

assign mac_compute_ipv4_che_U0_ap_start = 1'b1;

assign mac_finalize_ipv4_ch_U0_ap_continue = 1'b1;

assign mac_finalize_ipv4_ch_U0_ap_start = 1'b1;

assign mac_lshiftWordByOcte_U0_ap_continue = 1'b1;

assign mac_lshiftWordByOcte_U0_ap_start = 1'b1;

assign s_axis_arp_lookup_reply_V_TREADY = handle_arp_reply_U0_arpTableIn_V_TREADY;

assign s_axis_ip_TREADY = extract_ip_address_U0_s_axis_ip_TREADY;

endmodule //mac_ip_encode_top
